using System.Reflection;
using System.Reflection.Emit;

namespace SharpTS.Compilation;

/// <summary>
/// Holds references to runtime support types and methods emitted into compiled assemblies.
/// </summary>
/// <remarks>
/// Enables standalone DLLs without requiring SharpTS.dll at runtime. Contains references
/// to emitted types (TSFunction, TSRuntime) and helper methods (console.log, type coercion,
/// array/object operations, invocation helpers). These are generated by <see cref="RuntimeTypes"/>
/// and used by <see cref="ILEmitter"/> when emitting calls to runtime support code.
/// </remarks>
/// <seealso cref="RuntimeTypes"/>
/// <seealso cref="ILCompiler"/>
/// <seealso cref="ILEmitter"/>
public class EmittedRuntime
{
    /// <summary>Required lazy iterator adapter construction and helper declarations.</summary>
    public EmittedIteratorHelpersRuntime IteratorHelpers { get; } = new();


    /// <summary>Required iterable collection declarations, available before their bodies are emitted.</summary>
    public EmittedIteratorCollectionRuntime IteratorCollection { get; } = new();


    /// <summary>Required iterator lookup, result, close and dynamic protocol declarations.</summary>
    public EmittedIteratorProtocolRuntime IteratorProtocol { get; } = new();


    /// <summary>Required custom-iterator adapter declarations for this compilation.</summary>
    public EmittedIteratorWrapperRuntime IteratorWrappers { get; } = new();


    /// <summary>Required captured iterator-next lookup and invocation declarations.</summary>
    public EmittedIteratorRecordRuntime IteratorRecords { get; } = new();


    /// <summary>Optional async-generator interfaces with independently selected continuations and sync adaptation.</summary>
    public EmittedAsyncGeneratorRuntime? AsyncGenerators { get; private set; }

    internal void BeginAsyncGeneratorsEmission()
    {
        if (AsyncGenerators is not null)
            throw new InvalidOperationException("Async generator metadata emission has already started.");
        AsyncGenerators = new EmittedAsyncGeneratorRuntime();
    }

    public EmittedAsyncGeneratorRuntime RequireAsyncGenerators() => AsyncGenerators
        ?? throw new InvalidOperationException("Async generator runtime was not enabled for this compilation.");


    /// <summary>Required synchronous and native-number generator protocol declarations.</summary>
    public EmittedGeneratorRuntime Generators { get; } = new();

    /// <summary>Optional numeric iterator-result value type and baked member metadata.</summary>
    public EmittedStableIteratorResultRuntime? StableIteratorResults { get; private set; }

    internal void BeginStableIteratorResultsEmission()
    {
        if (StableIteratorResults is not null)
            throw new InvalidOperationException("Stable iterator result metadata emission has already started.");
        StableIteratorResults = new EmittedStableIteratorResultRuntime();
    }

    public EmittedStableIteratorResultRuntime RequireStableIteratorResults() => StableIteratorResults
        ?? throw new InvalidOperationException("Stable iterator result runtime was not enabled for this compilation.");


    /// <summary>Required argument-array pooling and spread-expansion metadata.</summary>
    public EmittedCallArgumentsRuntime CallArguments { get; } = new();


    /// <summary>Required dynamic function-construction and general constructor-value dispatch metadata.</summary>
    public EmittedDynamicConstructionRuntime DynamicConstruction { get; } = new();


    /// <summary>Required dynamic value, receiver-aware and zero-argument invocation metadata.</summary>
    public EmittedInvocationRuntime Invocation { get; } = new();


    /// <summary>Required reflected-method lookup, wrapper cache and staged callable metadata.</summary>
    public EmittedReflectedMethodRuntime ReflectedMethods { get; } = new();


    /// <summary>Required function property lookup and constructor-capability declarations.</summary>
    public EmittedFunctionIntrospectionRuntime FunctionIntrospection { get; } = new();


    /// <summary>Required Function prototype singleton and staged population declarations.</summary>
    public EmittedFunctionPrototypeRuntime FunctionPrototypes { get; } = new();


    /// <summary>Required function values, invocation caches and receiver-context declarations.</summary>
    public EmittedFunctionValueRuntime FunctionValues { get; } = new();

    /// <summary>Required argument-context and later branded argument-object declarations.</summary>
    public EmittedArgumentsRuntime Arguments { get; } = new();

    /// <summary>Required bound function and bind, call and apply wrapper declarations.</summary>
    public EmittedFunctionBindingRuntime FunctionBindings { get; } = new();


    /// <summary>Required function constructors, cached wrapper factory and dynamic construction declarations.</summary>
    public EmittedFunctionConstructionRuntime FunctionConstruction { get; } = new();


    /// <summary>Required function attributes, created before function wrapper emission.</summary>
    public EmittedFunctionAttributesRuntime FunctionAttributes { get; } = new();

    /// <summary>Required operator declarations and equality body lifecycle for one compilation.</summary>
    public EmittedOperatorRuntime Operators { get; } = new();


    /// <summary>Required named, computed, field and strict writing metadata for one compilation.</summary>
    public EmittedObjectWriteRuntime ObjectWrite { get; } = new();


    /// <summary>Required named, computed, field, list and element reading metadata for one compilation.</summary>
    public EmittedObjectReadRuntime ObjectRead { get; } = new();


    /// <summary>Required strict and non-strict property/index deletion metadata for one compilation.</summary>
    public EmittedObjectDeletionRuntime ObjectDeletion { get; } = new();


    /// <summary>Required object construction, spread, enumerable projection and rest helpers for one compilation.</summary>
    public EmittedObjectConstructionRuntime ObjectConstruction { get; } = new();


    /// <summary>Required Object value, entry, assignment, comparison and grouping operations for one compilation.</summary>
    public EmittedObjectOperationsRuntime ObjectOperations { get; } = new();


    /// <summary>Required own-property predicates and legacy accessor helpers for one compilation.</summary>
    public EmittedObjectOwnPropertiesRuntime ObjectOwnProperties { get; } = new();


    /// <summary>Required own-property key enumeration and Proxy key callbacks for one compilation.</summary>
    public EmittedObjectKeysRuntime ObjectKeys { get; } = new();


    /// <summary>Required Object prototype and prototype-chain operations for one compilation.</summary>
    public EmittedObjectPrototypeRuntime ObjectPrototypes { get; } = new();

    /// <summary>Required user-class prototype declarations and registration for one compilation.</summary>
    public EmittedClassPrototypeRuntime ClassPrototypes { get; } = new();


    /// <summary>Required public Object descriptor operations for this compilation.</summary>
    public EmittedObjectDescriptorRuntime ObjectDescriptors { get; } = new();

    /// <summary>Required Error types, prototypes and exception bridges for this compilation.</summary>
    public EmittedErrorRuntime Errors { get; } = new();

    /// <summary>Required object integrity and deleted-built-in metadata for this compilation.</summary>
    public EmittedObjectStateRuntime ObjectState { get; } = new();

    /// <summary>Required array storage metadata, emitted for every compilation.</summary>
    public EmittedArrayStorageRuntime ArrayStorage { get; } = new();

    /// <summary>Required object storage metadata, emitted for every compilation.</summary>
    public EmittedObjectStorageRuntime ObjectStorage { get; } = new();

    /// <summary>Required descriptor storage metadata, emitted for every compilation.</summary>
    public EmittedDescriptorStorageRuntime DescriptorStorage { get; } = new();

    /// <summary>Required Reflect reads and independently selected assignment, namespace and metadata capabilities.</summary>
    public EmittedReflectRuntime Reflect { get; } = new();

    /// <summary>Required JSON namespace and optional parse/stringify/raw-value metadata.</summary>
    public EmittedJsonRuntime Json { get; } = new();

    /// <summary>Required record marker, optional scalar declarations and early layout registries.</summary>
    public EmittedRecordStorageRuntime Records { get; } = new();

    /// <summary>Late shape fields on the generated Program type, completed after guest emission.</summary>
    public EmittedJsonShapeRegistry JsonShapes { get; } = new();

    /// <summary>Required array operation metadata, emitted for every compilation.</summary>
    public EmittedArrayOperationsRuntime ArrayOperations { get; } = new();

    /// <summary>
    /// Human-readable reasons this compilation emitted late binding into the SharpTS runtime
    /// assembly (e.g. "eval()", "Proxy", "Intl"). Populated during emission by
    /// <see cref="RequireSharpTSRuntime"/> at the feature gates / call sites that emit a
    /// <c>Type.GetType("…, SharpTS")</c> reflection path whose <em>normal</em> execution needs
    /// SharpTS.dll present. When non-empty, the build copies SharpTS.dll next to the output so
    /// the soft dependency resolves; when empty, the output is fully standalone.
    /// </summary>
    /// <remarks>
    /// Deliberately excludes graceful-fallback-only late binding that a normal program never
    /// reaches (e.g. the unconditional <c>process</c> helper), and pure-BCL features that emit
    /// no late binding at all (zlib, child_process, JSON). See <c>RuntimeEmitter.RuntimeClass</c>
    /// and <c>GlobalFunctionHandler.EmitEval</c> for the recording sites.
    /// </remarks>
    public SortedSet<string> RequiredSharpTSRuntimeReasons { get; } = new(StringComparer.Ordinal);

    /// <summary>
    /// Stable deployment capabilities corresponding to
    /// <see cref="RequiredSharpTSRuntimeReasons"/>. Build logic must use these flags rather than
    /// comparing human-readable reason strings.
    /// </summary>
    public SharpTSRuntimeRequirements RequiredSharpTSRuntimeRequirements { get; private set; }

    /// <summary>
    /// Records that <paramref name="reason"/> emitted a SharpTS-runtime late-binding path that a
    /// normal execution will hit. Idempotent.
    /// </summary>
    public void RequireSharpTSRuntime(
        string reason,
        SharpTSRuntimeRequirements requirements = SharpTSRuntimeRequirements.RuntimeAssembly)
    {
        RequiredSharpTSRuntimeReasons.Add(reason);
        RequiredSharpTSRuntimeRequirements |=
            requirements | SharpTSRuntimeRequirements.RuntimeAssembly;
    }

    /// <summary>
    /// Per-site hoisted regex-literal static fields (compiled-mode optimization),
    /// keyed by <c>Expr.RegexLiteral</c> node <em>identity</em> — see
    /// <see cref="RegexLiteralHoistAnalyzer"/>. Null when nothing was hoisted.
    /// <c>EmitRegexLiteral</c> loads the field (constructing the <c>$RegExp</c>
    /// once, lazily) instead of allocating a fresh instance per evaluation. Lives
    /// on the shared <see cref="EmittedRuntime"/> so it is reachable from every
    /// emission context (functions, arrows, state machines) with no extra
    /// threading.
    /// </summary>
    public Dictionary<SharpTS.Parsing.Expr.RegexLiteral, FieldBuilder>? RegexHoistFields { get; set; }

    /// <summary>Required undefined and lexical-initialization sentinels for this compilation.</summary>
    public EmittedSentinelRuntime Sentinels { get; } = new();


    /// <summary>Required namespace value declarations for this compilation.</summary>
    public EmittedNamespaceRuntime Namespaces { get; } = new();

    /// <summary>Required collection key identity declarations for this compilation.</summary>
    public EmittedCollectionKeysRuntime CollectionKeys { get; } = new();

    /// <summary>Map metadata, or null when the feature is omitted.</summary>
    public EmittedMapRuntime? Map { get; private set; }

    internal void BeginMapEmission()
    {
        if (Map is not null)
            throw new InvalidOperationException("Map metadata emission has already started.");
        Map = new EmittedMapRuntime();
    }

    public EmittedMapRuntime RequireMap() => Map
        ?? throw new InvalidOperationException("Map runtime was not enabled for this compilation.");

    /// <summary>Set metadata, or null when the feature is omitted.</summary>
    public EmittedSetRuntime? Set { get; private set; }

    internal void BeginSetEmission()
    {
        if (Set is not null)
            throw new InvalidOperationException("Set metadata emission has already started.");
        Set = new EmittedSetRuntime();
    }

    public EmittedSetRuntime RequireSet() => Set
        ?? throw new InvalidOperationException("Set runtime was not enabled for this compilation.");

    /// <summary>Required cooperative cancellation metadata, emitted independently of feature selection.</summary>
    public EmittedCancellationRuntime Cancellation { get; } = new();

    /// <summary>Required class-definition initialization and exception-unwrapping metadata.</summary>
    public EmittedClassInitializationRuntime ClassInitialization { get; } = new();

    // Constructor-free prototype objects for emitted user classes. Each user
    // class creates its prototype through a compiler-only constructor and
    // registers it here when the class definition is evaluated.

    // The emitted runtime helper class
    public TypeBuilder RuntimeType { get; set; } = null!;

    /// <summary>Required console metadata, emitted for every compilation.</summary>
    public EmittedConsoleRuntime Console { get; } = new();

    /// <summary>Required union-value interface declarations for this compilation.</summary>
    public EmittedUnionRuntime UnionValues { get; } = new();

    // Type coercion methods
    /// <summary>Required display and language string-conversion declarations.</summary>
    public EmittedStringCoercionRuntime StringCoercion { get; } = new();

    /// <summary>Required primitive-wrapper and default-hint conversion declarations.</summary>
    public EmittedBoxedPrimitiveRuntime BoxedPrimitives { get; } = new();

    /// <summary>Required numeric conversion declarations, including early RegExp coercion references.</summary>
    public EmittedNumericCoercionRuntime NumericCoercion { get; } = new();



    // Operator methods

    // Runtime dispatcher for built-in static member access on stored Type
    // tokens (issue #63). Returns a $TSFunction wrapper matching what the
    // compile-time ArrayStaticEmitter / NumberStaticEmitter / etc. would emit.
    public EmittedBuiltInStaticDispatchRuntime BuiltInStatics { get; } = new();
    /// <summary>Required null, undefined and Symbol receiver-validation metadata.</summary>
    public EmittedReceiverGuardRuntime ReceiverGuard { get; } = new();

    // $TSFunction static factory + instance cache: stable identity for
    // function-declaration references (see RuntimeEmitter.TSFunction.cs).
    // Exposed for iterator helpers' "skip index box for unary arrows" fast
    // path — read at runtime to detect callback arity without reflection.
    // True when the wrapped method's body reads JS `arguments`. Set via the
    // $CapturesArguments marker attribute (function declarations only — function
    // expressions already get _expectsThis=true via their __this param). Read by
    // the iterator-helper skip-index-box detection so it never drops the index
    // arg for a callback that could observe it through `arguments`.
    // Marker attribute applied to function-declaration methods that reference
    // `arguments`. Its ctor is invoked via CustomAttributeBuilder at method
    // definition; the type token is read back via MethodInfo.IsDefined.

    // Marker attribute applied to USER TypeScript function methods (declarations,
    // arrows/function expressions, methods, async stubs). When the wrapped method
    // carries it, $TSFunction.AdjustArgs pads omitted trailing arguments with the
    // `undefined` sentinel ($Undefined.Instance) instead of CLR null, matching JS
    // semantics and the direct-call path. Runtime built-ins stay unmarked and keep
    // null padding (their bodies use null-checks for optional-arg absence). (#640)

    // Attribute applied to emitted user methods with their ECMAScript Function.length.
    // CLR parameter metadata cannot represent the JS rule that arity stops at the first
    // default initializer, so reflective class-method wrappers read this value instead.

    // Marker attribute applied to a user function-expression / `this`-bearing arrow method whose
    // first emitted parameter is the synthetic `__this` receiver slot. $TSFunction reads it back via
    // IsDefined instead of matching on the parameter name, which keeps the check independent of the
    // Param table: a --ref-asm rewrite that mis-resolved a method's parameter list would otherwise
    // break the name-based check and shift value-call arguments by one. (NickNa.PEPacker carries
    // parameter names across the rewrite as of 1.0.3; the attribute keeps this independent of that.)
    // (#738)

    /// <summary>Required core string operations and prototype declarations.</summary>
    public EmittedStringRuntime Strings { get; } = new();

    // Object methods




    /// <summary>
    /// globalThis/global singleton — a sentinel object referenced from value
    /// position (`var root = globalThis`) so root/context detection in packages
    /// like lodash finds a real object instead of null (#271). Dynamic GetProperty/
    /// GetIndex/SetProperty/SetIndex ref-test against this field and route to
    /// GlobalThisGetProperty/GlobalThisSetProperty. The syntactic `globalThis.X`
    /// path is still intercepted at compile time by GlobalThisStaticEmitter.
    /// </summary>
    public EmittedGlobalObjectRuntime GlobalObject { get; } = new();



    /// <summary>Required .NET event-subscription metadata for this compilation.</summary>
    public EmittedEventSubscriptionRuntime EventSubscriptions { get; } = new();


    /// <summary>Required resource-disposal metadata for this compilation.</summary>
    public EmittedResourceDisposalRuntime ResourceDisposal { get; } = new();

    // Invocation methods


    // Function methods (bind/call/apply)

    // $Arguments : List<object> — marker subclass for the JS arguments object.
    // Used to brand sloppy-arguments instances so the brand-tagger returns
    // "[object Arguments]" and Array.isArray returns false per ECMA-262.

    // Generalized bind target — used when `.bind` is called on any callable other
    // than $TSFunction (arrays, maps, sets, etc.). Stores (target, boundArgs) and
    // prepends boundArgs to the call arguments on invocation. thisArg is ignored
    // because bound methods already capture their receiver.

    // Method callable wrapper for GetMember results (BuiltInMethod etc.)

    /// <summary>Required template strings, concatenation, raw conversion, and tag invocation metadata.</summary>
    public EmittedTemplateRuntime Templates { get; } = new();

    // Exception methods

    /// <summary>Required enum reverse-lookup metadata for this compilation.</summary>
    public EmittedEnumRuntime Enums { get; } = new();

    /// <summary>Required Math singleton, numeric adapters and exact summation declarations.</summary>
    public EmittedMathRuntime Math { get; } = new();

    /// <summary>Required BigInt prototype/numeric metadata with optional BigInt operations.</summary>
    public EmittedBigIntRuntime BigInt { get; } = new();

    /// <summary>Required truthiness and Boolean prototype declarations.</summary>
    public EmittedBooleanRuntime Booleans { get; } = new();


    // General invocation helper

    /// <summary>Required Symbol primitive, identity, storage and prototype metadata for this compilation.</summary>
    public EmittedSymbolRuntime Symbols { get; } = new();

    // Numeric increment/decrement.

    /// <summary>Promise metadata, or null when Promise support is tree-shaken.</summary>
    public EmittedPromiseRuntime? Promise { get; private set; }

    internal void BeginPromiseEmission()
    {
        if (Promise is not null)
            throw new InvalidOperationException("Promise metadata emission has already started.");
        Promise = new EmittedPromiseRuntime();
    }

    public EmittedPromiseRuntime RequirePromise() => Promise
        ?? throw new InvalidOperationException("Promise runtime was not enabled for this compilation.");

    /// <summary>Required timeout handles and virtual timer queue operations.</summary>
    public EmittedTimerRuntime Timers { get; } = new();

    /// <summary>Required shared FIFO queue for callbacks and Promise jobs.</summary>
    public EmittedMicrotaskRuntime Microtasks { get; } = new();

    /// <summary>Promise-based timers, available under the existing UsesPromise gate.</summary>
    public EmittedTimerPromiseRuntime? TimerPromises { get; private set; }

    internal void BeginTimerPromiseEmission()
    {
        if (TimerPromises is not null)
            throw new InvalidOperationException("Timer promise metadata emission has already started.");
        TimerPromises = new EmittedTimerPromiseRuntime();
    }

    public EmittedTimerPromiseRuntime RequireTimerPromises() => TimerPromises
        ?? throw new InvalidOperationException("Timer promise runtime was not enabled for this compilation.");

    // Number methods
    /// <summary>Required Number parsing, formatting and prototype declarations.</summary>
    public EmittedNumberRuntime Numbers { get; } = new();

    /// <summary>Required URI component conversion declarations for this compilation.</summary>
    public EmittedUriComponentRuntime UriComponents { get; } = new();

    /// <summary>WeakMap metadata, or null when the feature is omitted.</summary>
    public EmittedWeakMapRuntime? WeakMap { get; private set; }

    internal void BeginWeakMapEmission()
    {
        if (WeakMap is not null)
            throw new InvalidOperationException("WeakMap metadata emission has already started.");
        WeakMap = new EmittedWeakMapRuntime();
    }

    public EmittedWeakMapRuntime RequireWeakMap() => WeakMap
        ?? throw new InvalidOperationException("WeakMap runtime was not enabled for this compilation.");

    /// <summary>WeakSet metadata, or null when the feature is omitted.</summary>
    public EmittedWeakSetRuntime? WeakSet { get; private set; }

    internal void BeginWeakSetEmission()
    {
        if (WeakSet is not null)
            throw new InvalidOperationException("WeakSet metadata emission has already started.");
        WeakSet = new EmittedWeakSetRuntime();
    }

    public EmittedWeakSetRuntime RequireWeakSet() => WeakSet
        ?? throw new InvalidOperationException("WeakSet runtime was not enabled for this compilation.");

    /// <summary>WeakRef metadata, or null when the feature is omitted.</summary>
    public EmittedWeakRefRuntime? WeakRef { get; private set; }

    internal void BeginWeakRefEmission()
    {
        if (WeakRef is not null)
            throw new InvalidOperationException("WeakRef metadata emission has already started.");
        WeakRef = new EmittedWeakRefRuntime();
    }

    public EmittedWeakRefRuntime RequireWeakRef() => WeakRef
        ?? throw new InvalidOperationException("WeakRef runtime was not enabled for this compilation.");

    /// <summary>Required finalization poke table and optional registry implementation for this compilation.</summary>
    public EmittedFinalizationRegistryRuntime FinalizationRegistry { get; } = new();

    /// <summary>Proxy factory declarations, or null when Proxy is omitted.</summary>
    public EmittedProxyConstructionRuntime? ProxyConstruction { get; private set; }

    internal void BeginProxyConstructionEmission()
    {
        if (ProxyConstruction is not null)
            throw new InvalidOperationException("Proxy-construction metadata emission has already started.");
        ProxyConstruction = new EmittedProxyConstructionRuntime();
    }

    public EmittedProxyConstructionRuntime RequireProxyConstruction() => ProxyConstruction
        ?? throw new InvalidOperationException("Proxy construction was not enabled for this compilation.");

    /// <summary>Required module registry metadata with optional CommonJS and dynamic-import declarations.</summary>
    public EmittedModuleRuntime Modules { get; } = new();

    /// <summary>Required Date prototype declarations with optional Date type and operation metadata.</summary>
    public EmittedDateRuntime Dates { get; } = new();

    /// <summary>Required RegExp prototype declarations and optional type, operation and protocol metadata.</summary>
    public EmittedRegExpRuntime RegExps { get; } = new();

    // groupBy support

    // Error support - emitted types for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSError and subclasses

    // $Error base class

    // $TypeError

    // $RangeError

    // $ReferenceError

    // $SyntaxError

    // $URIError

    // $EvalError

    // $AggregateError

    // Error helper methods in $Runtime

    // $ThrownValueException : Exception — the allocation-light carrier for a
    // guest `throw` value. Message is derived lazily at a host boundary.


    /// <summary>Required object-field interface and baked methods for this compilation.</summary>
    public EmittedObjectFieldRuntime ObjectFields { get; } = new();


    // Iterator protocol helper methods







    // Iterator helper methods (ES2025 Iterator Helpers)

    // Iterator helper lazy wrapper types

    // OS module methods
    /// <summary>OS metadata, or null when OS helpers are omitted.</summary>
    public EmittedOsRuntime? Os { get; private set; }

    internal void BeginOsEmission()
    {
        if (Os is not null)
            throw new InvalidOperationException("OS metadata emission has already started.");
        Os = new EmittedOsRuntime();
    }

    public EmittedOsRuntime RequireOs() => Os
        ?? throw new InvalidOperationException("OS runtime was not enabled for this compilation.");

    /// <summary>Filesystem data and synchronous I/O metadata, absent when UsesFs is off.</summary>
    public EmittedFileSystemRuntime? FileSystem { get; private set; }

    internal void BeginFileSystemEmission()
    {
        if (FileSystem is not null)
            throw new InvalidOperationException("Filesystem metadata emission has already started.");
        FileSystem = new EmittedFileSystemRuntime();
    }

    public EmittedFileSystemRuntime RequireFileSystem() => FileSystem
        ?? throw new InvalidOperationException("Filesystem runtime was not enabled for this compilation.");

    /// <summary>ArrayBuffer metadata, or null when the typed-array family is tree-shaken.</summary>
    public EmittedArrayBufferRuntime? ArrayBuffer { get; private set; }

    internal void BeginArrayBufferEmission()
    {
        if (ArrayBuffer is not null)
            throw new InvalidOperationException("ArrayBuffer metadata emission has already started.");
        ArrayBuffer = new EmittedArrayBufferRuntime();
    }

    public EmittedArrayBufferRuntime RequireArrayBuffer() => ArrayBuffer
        ?? throw new InvalidOperationException("ArrayBuffer runtime was not enabled for this compilation.");

    /// <summary>SharedArrayBuffer metadata, or null when the typed-array family is tree-shaken.</summary>
    public EmittedSharedArrayBufferRuntime? SharedArrayBuffer { get; private set; }

    internal void BeginSharedArrayBufferEmission()
    {
        if (SharedArrayBuffer is not null)
            throw new InvalidOperationException("SharedArrayBuffer metadata emission has already started.");
        SharedArrayBuffer = new EmittedSharedArrayBufferRuntime();
    }

    public EmittedSharedArrayBufferRuntime RequireSharedArrayBuffer() => SharedArrayBuffer
        ?? throw new InvalidOperationException("SharedArrayBuffer runtime was not enabled for this compilation.");

    /// <summary>DataView metadata, or null when the typed-array family is tree-shaken.</summary>
    public EmittedDataViewRuntime? DataView { get; private set; }

    internal void BeginDataViewEmission()
    {
        if (DataView is not null)
            throw new InvalidOperationException("DataView metadata emission has already started.");
        DataView = new EmittedDataViewRuntime();
    }

    public EmittedDataViewRuntime RequireDataView() => DataView
        ?? throw new InvalidOperationException("DataView runtime was not enabled for this compilation.");

    /// <summary>Required TypedArray detection metadata with optional implementation declarations.</summary>
    public EmittedTypedArrayRuntime TypedArrays { get; } = new();

    /// <summary>Filesystem async metadata, or null when UsesFs is off.</summary>
    public EmittedFileSystemAsyncRuntime? FileSystemAsync { get; private set; }

    internal void BeginFileSystemAsyncEmission()
    {
        if (FileSystemAsync is not null)
            throw new InvalidOperationException("Filesystem async metadata emission has already started.");
        FileSystemAsync = new EmittedFileSystemAsyncRuntime();
    }

    public EmittedFileSystemAsyncRuntime RequireFileSystemAsync() => FileSystemAsync
        ?? throw new InvalidOperationException("Filesystem async runtime was not enabled for this compilation.");

    /// <summary>Required process metadata, with explicit optional stream and hosted declarations.</summary>
    public EmittedProcessRuntime Process { get; } = new();

    /// <summary>Required class accessor/method registry declarations, with early shells and later bodies.</summary>
    public EmittedSymbolAccessorRuntime SymbolAccessors { get; } = new();

    /// <summary>Node crypto metadata, or null when crypto is tree-shaken from this compilation.</summary>
    public EmittedCryptoRuntime? Crypto { get; private set; }

    internal void BeginCryptoEmission()
    {
        if (Crypto is not null)
            throw new InvalidOperationException("Crypto metadata emission has already started.");
        Crypto = new EmittedCryptoRuntime();
    }

    public EmittedCryptoRuntime RequireCrypto() => Crypto
        ?? throw new InvalidOperationException("Crypto runtime was not enabled for this compilation.");

    // The global function-cache field is always declared; Web API metadata is optional.
    public EmittedFetchRuntime Fetch { get; } = new();

    /// <summary>HTTP module/server metadata, or null when HTTP is tree-shaken.</summary>
    public EmittedHttpRuntime? Http { get; private set; }

    internal void BeginHttpEmission()
    {
        if (Http is not null)
            throw new InvalidOperationException("HTTP metadata emission has already started.");
        Http = new EmittedHttpRuntime();
    }

    public EmittedHttpRuntime RequireHttp() => Http
        ?? throw new InvalidOperationException("HTTP runtime was not enabled for this compilation.");

    /// <summary>TCP/IPC metadata, or null when net is tree-shaken from this compilation.</summary>
    public EmittedNetRuntime? Net { get; private set; }

    internal void BeginNetEmission()
    {
        if (Net is not null)
            throw new InvalidOperationException("Net metadata emission has already started.");
        Net = new EmittedNetRuntime();
    }

    public EmittedNetRuntime RequireNet() => Net
        ?? throw new InvalidOperationException("Net runtime was not enabled for this compilation.");

    /// <summary>TLS metadata, or null when TLS is tree-shaken from this compilation.</summary>
    public EmittedTlsRuntime? Tls { get; private set; }

    internal void BeginTlsEmission()
    {
        if (Tls is not null)
            throw new InvalidOperationException("TLS metadata emission has already started.");
        Tls = new EmittedTlsRuntime();
    }

    public EmittedTlsRuntime RequireTls() => Tls
        ?? throw new InvalidOperationException("TLS runtime was not enabled for this compilation.");

    /// <summary>Datagram metadata, or null when dgram is tree-shaken from this compilation.</summary>
    public EmittedDgramRuntime? Dgram { get; private set; }

    internal void BeginDgramEmission()
    {
        if (Dgram is not null)
            throw new InvalidOperationException("Dgram metadata emission has already started.");
        Dgram = new EmittedDgramRuntime();
    }

    public EmittedDgramRuntime RequireDgram() => Dgram
        ?? throw new InvalidOperationException("Dgram runtime was not enabled for this compilation.");

    /// <summary>Node Buffer metadata, or null when Buffer is tree-shaken.</summary>
    public EmittedBufferRuntime? Buffer { get; private set; }

    internal void BeginBufferEmission(bool hasTypedArrayCopy)
    {
        if (Buffer is not null)
            throw new InvalidOperationException("Buffer metadata emission has already started.");
        Buffer = new EmittedBufferRuntime(hasTypedArrayCopy);
    }

    public EmittedBufferRuntime RequireBuffer() => Buffer
        ?? throw new InvalidOperationException("Buffer runtime was not enabled for this compilation.");

    /// <summary>Text-encoding metadata, or null when the feature is omitted.</summary>
    public EmittedTextEncodingRuntime? TextEncoding { get; private set; }

    internal void BeginTextEncodingEmission()
    {
        if (TextEncoding is not null)
            throw new InvalidOperationException("Text-encoding metadata emission has already started.");
        TextEncoding = new EmittedTextEncodingRuntime();
    }

    public EmittedTextEncodingRuntime RequireTextEncoding() => TextEncoding
        ?? throw new InvalidOperationException("Text-encoding runtime was not enabled for this compilation.");

    /// <summary>Required inspection metadata used by console.dir in every compilation.</summary>
    public EmittedInspectionRuntime Inspection { get; } = new();

    /// <summary>Readline metadata, or null when the feature is omitted.</summary>
    public EmittedReadlineRuntime? Readline { get; private set; }

    internal void BeginReadlineEmission()
    {
        if (Readline is not null)
            throw new InvalidOperationException("Readline metadata emission has already started.");
        Readline = new EmittedReadlineRuntime();
    }

    public EmittedReadlineRuntime RequireReadline() => Readline
        ?? throw new InvalidOperationException("Readline runtime was not enabled for this compilation.");

    /// <summary>Child-process metadata, or null when child_process is omitted.</summary>
    public EmittedChildProcessRuntime? ChildProcess { get; private set; }

    internal void BeginChildProcessEmission()
    {
        if (ChildProcess is not null)
            throw new InvalidOperationException("Child-process metadata emission has already started.");
        ChildProcess = new EmittedChildProcessRuntime();
    }

    public EmittedChildProcessRuntime RequireChildProcess() => ChildProcess
        ?? throw new InvalidOperationException("Child-process runtime was not enabled for this compilation.");

    // Querystring module methods

    /// <summary>Zlib metadata, or null when zlib is tree-shaken from this compilation.</summary>
    public EmittedZlibRuntime? Zlib { get; private set; }

    internal void BeginZlibEmission()
    {
        if (Zlib is not null)
            throw new InvalidOperationException("Zlib metadata emission has already started.");
        Zlib = new EmittedZlibRuntime();
    }

    public EmittedZlibRuntime RequireZlib() => Zlib
        ?? throw new InvalidOperationException("Zlib runtime was not enabled for this compilation.");

    /// <summary>Required EventEmitter types, listener storage, and dispatch metadata.</summary>
    public EmittedEventEmitterRuntime EventEmitter { get; } = new();

    /// <summary>AsyncLocalStorage metadata, or null when the feature is omitted.</summary>
    public EmittedAsyncLocalStorageRuntime? AsyncLocalStorage { get; private set; }

    internal void BeginAsyncLocalStorageEmission()
    {
        if (AsyncLocalStorage is not null)
            throw new InvalidOperationException("AsyncLocalStorage metadata emission has already started.");
        AsyncLocalStorage = new EmittedAsyncLocalStorageRuntime();
    }

    public EmittedAsyncLocalStorageRuntime RequireAsyncLocalStorage() => AsyncLocalStorage
        ?? throw new InvalidOperationException("AsyncLocalStorage runtime was not enabled for this compilation.");

    /// <summary>AbortController/AbortSignal metadata, or null when the feature is omitted.</summary>
    public EmittedAbortRuntime? Abort { get; private set; }

    internal void BeginAbortEmission()
    {
        if (Abort is not null)
            throw new InvalidOperationException("Abort metadata emission has already started.");
        Abort = new EmittedAbortRuntime();
    }

    public EmittedAbortRuntime RequireAbort() => Abort
        ?? throw new InvalidOperationException("Abort runtime was not enabled for this compilation.");

    /// <summary>Intl factory and namespace metadata, or null when the feature is omitted.</summary>
    public EmittedIntlRuntime? Intl { get; private set; }

    internal void BeginIntlEmission()
    {
        if (Intl is not null)
            throw new InvalidOperationException("Intl metadata emission has already started.");
        Intl = new EmittedIntlRuntime();
    }

    public EmittedIntlRuntime RequireIntl() => Intl
        ?? throw new InvalidOperationException("Intl runtime was not enabled for this compilation.");

    /// <summary>Required NodeError declarations shared by filesystem and process emission.</summary>
    public EmittedNodeErrorRuntime NodeErrors { get; } = new();

    /// <summary>TTY primitive metadata, or null when the feature is omitted.</summary>
    public EmittedTtyRuntime? Tty { get; private set; }

    internal void BeginTtyEmission()
    {
        if (Tty is not null)
            throw new InvalidOperationException("TTY metadata emission has already started.");
        Tty = new EmittedTtyRuntime();
    }

    public EmittedTtyRuntime RequireTty() => Tty
        ?? throw new InvalidOperationException("TTY runtime was not enabled for this compilation.");

    /// <summary>Performance primitive metadata, or null when the feature is omitted.</summary>
    public EmittedPerformanceRuntime? Performance { get; private set; }

    internal void BeginPerformanceEmission()
    {
        if (Performance is not null)
            throw new InvalidOperationException("Performance metadata emission has already started.");
        Performance = new EmittedPerformanceRuntime();
    }

    public EmittedPerformanceRuntime RequirePerformance() => Performance
        ?? throw new InvalidOperationException("Performance runtime was not enabled for this compilation.");

    /// <summary>Node stream metadata, or null when Node streams are tree-shaken.</summary>
    public EmittedNodeStreamRuntime? NodeStreams { get; private set; }

    internal void BeginNodeStreamEmission(bool hasAbortSignal)
    {
        if (NodeStreams is not null)
            throw new InvalidOperationException("Node stream metadata emission has already started.");
        NodeStreams = new EmittedNodeStreamRuntime(hasAbortSignal);
    }

    public EmittedNodeStreamRuntime RequireNodeStreams() => NodeStreams
        ?? throw new InvalidOperationException("Node streams were not enabled for this compilation.");

    /// <summary>Filesystem stream metadata, or null when UsesFs is off.</summary>
    public EmittedFileSystemStreamRuntime? FileSystemStreams { get; private set; }

    internal void BeginFileSystemStreamEmission()
    {
        if (FileSystemStreams is not null)
            throw new InvalidOperationException("Filesystem stream metadata emission has already started.");
        FileSystemStreams = new EmittedFileSystemStreamRuntime();
    }

    public EmittedFileSystemStreamRuntime RequireFileSystemStreams() => FileSystemStreams
        ?? throw new InvalidOperationException("Filesystem stream runtime was not enabled for this compilation.");

    /// <summary>Filesystem watcher metadata, or null when UsesFs is off.</summary>
    public EmittedFileSystemWatcherRuntime? FileSystemWatchers { get; private set; }

    internal void BeginFileSystemWatcherEmission()
    {
        if (FileSystemWatchers is not null)
            throw new InvalidOperationException("Filesystem watcher metadata emission has already started.");
        FileSystemWatchers = new EmittedFileSystemWatcherRuntime();
    }

    public EmittedFileSystemWatcherRuntime RequireFileSystemWatchers() => FileSystemWatchers
        ?? throw new InvalidOperationException("Filesystem watcher runtime was not enabled for this compilation.");

    // Built-in module methods (module name -> method name -> MethodBuilder)
    // Used for creating TSFunction wrappers when importing named exports
    private readonly Dictionary<string, Dictionary<string, MethodBuilder>> _builtInModuleMethods = new();

    /// <summary>
    /// Registers a built-in module method.
    /// </summary>
    public void RegisterBuiltInModuleMethod(string moduleName, string methodName, MethodBuilder method)
    {
        if (!_builtInModuleMethods.TryGetValue(moduleName, out var methods))
        {
            methods = new Dictionary<string, MethodBuilder>();
            _builtInModuleMethods[moduleName] = methods;
        }
        methods[methodName] = method;
    }

    /// <summary>
    /// Gets a built-in module method for creating a TSFunction wrapper.
    /// </summary>
    public MethodBuilder? GetBuiltInModuleMethod(string moduleName, string methodName)
    {
        if (_builtInModuleMethods.TryGetValue(moduleName, out var methods) &&
            methods.TryGetValue(methodName, out var method))
        {
            return method;
        }
        return null;
    }

    // ============================================================
    // Worker Threads Support
    // ============================================================

    /// <summary>Atomics declarations, or null when typed-array implementation is omitted.</summary>
    public EmittedAtomicsRuntime? Atomics { get; private set; }

    internal void BeginAtomicsEmission()
    {
        if (Atomics is not null)
            throw new InvalidOperationException("Atomics metadata emission has already started.");
        Atomics = new EmittedAtomicsRuntime();
    }

    public EmittedAtomicsRuntime RequireAtomics() => Atomics
        ?? throw new InvalidOperationException("Atomics runtime was not enabled for this compilation.");

    /// <summary>Required MessagePort/MessageChannel declarations and peer-access metadata.</summary>
    public EmittedMessageChannelRuntime MessageChannels { get; } = new();

    /// <summary>Required worker factory, context, environment, and receive-bridge declarations.</summary>
    public EmittedWorkerRuntime Workers { get; } = new();

    /// <summary>Required structured-clone helper and dedicated receiver-side clone-failure exception.</summary>
    public EmittedStructuredCloneRuntime StructuredClone { get; } = new();

    /// <summary>DNS metadata, or null when DNS is tree-shaken from this compilation.</summary>
    public EmittedDnsRuntime? Dns { get; private set; }

    internal void BeginDnsEmission()
    {
        if (Dns is not null)
            throw new InvalidOperationException("DNS metadata emission has already started.");
        Dns = new EmittedDnsRuntime();
    }

    public EmittedDnsRuntime RequireDns() => Dns
        ?? throw new InvalidOperationException("DNS runtime was not enabled for this compilation.");

    // cluster module — late-bound bridge into SharpTS.dll (#1171). Workers run the
    // entry script interpreted in-process (the worker_threads pattern), so the whole
    // module surface routes through ClusterCompiledBridge for coherent state.
    public EmittedClusterRuntime? Cluster { get; private set; }

    internal void BeginClusterEmission()
    {
        if (Cluster is not null)
            throw new InvalidOperationException("Cluster metadata emission has already started.");
        Cluster = new EmittedClusterRuntime();
    }

    public EmittedClusterRuntime RequireCluster() => Cluster
        ?? throw new InvalidOperationException("Cluster runtime was not enabled for this compilation.");

    /// <summary>BroadcastChannel declarations, or null when the feature is omitted.</summary>
    public EmittedBroadcastChannelRuntime? BroadcastChannel { get; private set; }

    internal void BeginBroadcastChannelEmission()
    {
        if (BroadcastChannel is not null)
            throw new InvalidOperationException("BroadcastChannel metadata emission has already started.");
        BroadcastChannel = new EmittedBroadcastChannelRuntime();
    }

    public EmittedBroadcastChannelRuntime RequireBroadcastChannel() => BroadcastChannel
        ?? throw new InvalidOperationException("BroadcastChannel runtime was not enabled for this compilation.");

    /// <summary>Required scheduler and synchronization-context metadata, with optional hosted hooks.</summary>
    public EmittedEventLoopRuntime EventLoop { get; } = new();

    /// <summary>VM metadata, or null when the feature is omitted.</summary>
    public EmittedVmRuntime? Vm { get; private set; }

    internal void BeginVmEmission()
    {
        if (Vm is not null)
            throw new InvalidOperationException("VM metadata emission has already started.");
        Vm = new EmittedVmRuntime();
    }

    public EmittedVmRuntime RequireVm() => Vm
        ?? throw new InvalidOperationException("VM runtime was not enabled for this compilation.");

    /// <summary>Source-execution metadata, or null when the feature is omitted.</summary>
    public EmittedSourceExecutionRuntime? SourceExecution { get; private set; }

    internal void BeginSourceExecutionEmission()
    {
        if (SourceExecution is not null)
            throw new InvalidOperationException("Source-execution metadata emission has already started.");
        SourceExecution = new EmittedSourceExecutionRuntime();
    }

    public EmittedSourceExecutionRuntime RequireSourceExecution() => SourceExecution
        ?? throw new InvalidOperationException("Source-execution runtime was not enabled for this compilation.");

    /// <summary>Web stream metadata, or null when Web streams are tree-shaken.</summary>
    public EmittedWebStreamRuntime? WebStreams { get; private set; }

    internal void BeginWebStreamEmission()
    {
        if (WebStreams is not null)
            throw new InvalidOperationException("Web stream metadata emission has already started.");
        WebStreams = new EmittedWebStreamRuntime();
    }

    public EmittedWebStreamRuntime RequireWebStreams() => WebStreams
        ?? throw new InvalidOperationException("Web streams were not enabled for this compilation.");

    // WebCrypto (#1063) — GetWebCryptoObject() → the $WebCrypto singleton
    // (globalThis.crypto / crypto.webcrypto). Reserved in DefineRuntimeClassPhase1;
    // body filled by EmitWebCryptoTypes (or the null stub when crypto is unused).
    public EmittedWebCryptoRuntime WebCrypto { get; } = new();
}
