using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Reflection.Emit;

namespace SharpTS.Compilation;

public partial class RuntimeEmitter
{
    /// <summary>Emits OS lookup with literal preservation, family filtering and stable result ordering.</summary>
    private void EmitDnsLookup(TypeBuilder typeBuilder, EmittedRuntime runtime, FieldBuilder resultOrderField)
    {
        var method = typeBuilder.DefineMethod("DnsLookup", MethodAttributes.Public | MethodAttributes.Static,
            _types.Object, [_types.Object, _types.Object]);
        runtime.RequireDns().Lookup = method;
        var il = method.GetILGenerator();
        var hostname = il.DeclareLocal(typeof(string));
        var familyValue = il.DeclareLocal(typeof(object));
        var family = il.DeclareLocal(typeof(int));
        var all = il.DeclareLocal(typeof(bool));
        var order = il.DeclareLocal(typeof(string));
        var preferredFamily = il.DeclareLocal(typeof(int));
        var literal = il.DeclareLocal(typeof(IPAddress));
        var isLiteral = il.DeclareLocal(typeof(bool));
        var addresses = il.DeclareLocal(typeof(IPAddress[]));
        var address = il.DeclareLocal(typeof(IPAddress));
        var addressFamily = il.DeclareLocal(typeof(int));
        var results = il.DeclareLocal(typeof(List<object>));
        var result = il.DeclareLocal(typeof(object));
        var index = il.DeclareLocal(typeof(int));
        var pass = il.DeclareLocal(typeof(int));
        var done = il.DefineLabel();

        void Property(string name)
        {
            il.Emit(OpCodes.Ldarg_1);
            il.Emit(OpCodes.Ldstr, name);
            il.Emit(OpCodes.Call, runtime.ObjectRead.Property);
        }
        void EqualString(string value)
        {
            il.Emit(OpCodes.Ldstr, value);
            il.Emit(OpCodes.Call, typeof(string).GetMethod("op_Equality", [typeof(string), typeof(string)])!);
        }

        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Isinst, typeof(string));
        il.Emit(OpCodes.Stloc, hostname);
        var validHost = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Brtrue, validHost);
        il.Emit(OpCodes.Ldstr, "Runtime Error: dns.lookup requires a hostname string");
        il.Emit(OpCodes.Newobj, typeof(Exception).GetConstructor([typeof(string)])!);
        il.Emit(OpCodes.Throw);
        il.MarkLabel(validHost);

        il.Emit(OpCodes.Ldsfld, resultOrderField);
        il.Emit(OpCodes.Stloc, order);
        var optionsDone = il.DefineLabel();
        var objectOptions = il.DefineLabel();
        var familyReady = il.DefineLabel();
        il.Emit(OpCodes.Ldarg_1);
        il.Emit(OpCodes.Brfalse, optionsDone);
        il.Emit(OpCodes.Ldarg_1);
        il.Emit(OpCodes.Isinst, runtime.Sentinels.UndefinedType);
        il.Emit(OpCodes.Brtrue, optionsDone);
        il.Emit(OpCodes.Ldarg_1);
        il.Emit(OpCodes.Isinst, typeof(double));
        il.Emit(OpCodes.Brfalse, objectOptions);
        il.Emit(OpCodes.Ldarg_1);
        il.Emit(OpCodes.Stloc, familyValue);
        il.Emit(OpCodes.Br, familyReady);
        il.MarkLabel(objectOptions);
        Property("family");
        il.Emit(OpCodes.Stloc, familyValue);
        Property("all");
        il.Emit(OpCodes.Call, runtime.Booleans.IsTruthy);
        il.Emit(OpCodes.Stloc, all);
        Property("order");
        il.Emit(OpCodes.Isinst, typeof(string));
        var explicitOrder = il.DeclareLocal(typeof(string));
        il.Emit(OpCodes.Stloc, explicitOrder);
        var legacyOrder = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, explicitOrder);
        il.Emit(OpCodes.Brfalse, legacyOrder);
        il.Emit(OpCodes.Ldloc, explicitOrder);
        il.Emit(OpCodes.Stloc, order);
        il.Emit(OpCodes.Br, familyReady);
        il.MarkLabel(legacyOrder);
        Property("verbatim");
        var verbatim = il.DeclareLocal(typeof(object));
        il.Emit(OpCodes.Stloc, verbatim);
        il.Emit(OpCodes.Ldloc, verbatim);
        il.Emit(OpCodes.Isinst, typeof(bool));
        il.Emit(OpCodes.Brfalse, familyReady);
        var verbatimTrue = il.DefineLabel();
        var verbatimDone = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, verbatim);
        il.Emit(OpCodes.Unbox_Any, typeof(bool));
        il.Emit(OpCodes.Brtrue, verbatimTrue);
        il.Emit(OpCodes.Ldstr, "ipv4first");
        il.Emit(OpCodes.Br, verbatimDone);
        il.MarkLabel(verbatimTrue);
        il.Emit(OpCodes.Ldstr, "verbatim");
        il.MarkLabel(verbatimDone);
        il.Emit(OpCodes.Stloc, order);

        il.MarkLabel(familyReady);
        il.Emit(OpCodes.Ldloc, familyValue);
        il.Emit(OpCodes.Isinst, typeof(double));
        il.Emit(OpCodes.Brfalse, optionsDone);
        il.Emit(OpCodes.Ldloc, familyValue);
        il.Emit(OpCodes.Unbox_Any, typeof(double));
        il.Emit(OpCodes.Conv_I4);
        il.Emit(OpCodes.Stloc, family);
        il.MarkLabel(optionsDone);

        // Stable partition in two passes, preserving resolver order within each family.
        var orderDone = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, family);
        il.Emit(OpCodes.Brtrue, orderDone);
        il.Emit(OpCodes.Ldloc, order);
        EqualString("ipv4first");
        var tryIpv6 = il.DefineLabel();
        il.Emit(OpCodes.Brfalse, tryIpv6);
        il.Emit(OpCodes.Ldc_I4_4);
        il.Emit(OpCodes.Stloc, preferredFamily);
        il.Emit(OpCodes.Br, orderDone);
        il.MarkLabel(tryIpv6);
        il.Emit(OpCodes.Ldloc, order);
        EqualString("ipv6first");
        il.Emit(OpCodes.Brfalse, orderDone);
        il.Emit(OpCodes.Ldc_I4_6);
        il.Emit(OpCodes.Stloc, preferredFamily);
        il.MarkLabel(orderDone);

        il.BeginExceptionBlock();
        var resolve = il.DefineLabel();
        var literalReady = il.DefineLabel();
        var addressesReady = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Ldloca, literal);
        il.Emit(OpCodes.Call, typeof(IPAddress).GetMethod("TryParse", [typeof(string), typeof(IPAddress).MakeByRefType()])!);
        il.Emit(OpCodes.Brfalse, resolve);
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Ldloc, literal);
        il.Emit(OpCodes.Callvirt, typeof(IPAddress).GetMethod("ToString", Type.EmptyTypes)!);
        il.Emit(OpCodes.Call, typeof(string).GetMethod("op_Equality", [typeof(string), typeof(string)])!);
        il.Emit(OpCodes.Brtrue, literalReady);
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Ldc_I4, (int)':');
        il.Emit(OpCodes.Callvirt, typeof(string).GetMethod("Contains", [typeof(char)])!);
        il.Emit(OpCodes.Brfalse, resolve);
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Ldc_I4, (int)'[');
        il.Emit(OpCodes.Callvirt, typeof(string).GetMethod("StartsWith", [typeof(char)])!);
        il.Emit(OpCodes.Brtrue, resolve);
        il.MarkLabel(literalReady);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Stloc, isLiteral);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Stloc, family);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Stloc, preferredFamily);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Newarr, typeof(IPAddress));
        il.Emit(OpCodes.Dup);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Ldloc, literal);
        il.Emit(OpCodes.Stelem_Ref);
        il.Emit(OpCodes.Stloc, addresses);
        il.Emit(OpCodes.Br, addressesReady);
        il.MarkLabel(resolve);
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Call, typeof(Dns).GetMethod("GetHostAddresses", [typeof(string)])!);
        il.Emit(OpCodes.Stloc, addresses);
        il.MarkLabel(addressesReady);
        il.Emit(OpCodes.Newobj, typeof(List<object>).GetConstructor(Type.EmptyTypes)!);
        il.Emit(OpCodes.Stloc, results);

        var passStart = il.DefineLabel();
        var loop = il.DefineLabel();
        var next = il.DefineLabel();
        var passDone = il.DefineLabel();
        il.MarkLabel(passStart);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Stloc, index);
        il.MarkLabel(loop);
        il.Emit(OpCodes.Ldloc, index);
        il.Emit(OpCodes.Ldloc, addresses);
        il.Emit(OpCodes.Ldlen);
        il.Emit(OpCodes.Conv_I4);
        il.Emit(OpCodes.Bge, passDone);
        il.Emit(OpCodes.Ldloc, addresses);
        il.Emit(OpCodes.Ldloc, index);
        il.Emit(OpCodes.Ldelem_Ref);
        il.Emit(OpCodes.Stloc, address);
        il.Emit(OpCodes.Ldc_I4_6);
        il.Emit(OpCodes.Stloc, addressFamily);
        var familyKnown = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, address);
        il.Emit(OpCodes.Callvirt, typeof(IPAddress).GetProperty("AddressFamily")!.GetMethod!);
        il.Emit(OpCodes.Ldc_I4, (int)AddressFamily.InterNetwork);
        il.Emit(OpCodes.Bne_Un, familyKnown);
        il.Emit(OpCodes.Ldc_I4_4);
        il.Emit(OpCodes.Stloc, addressFamily);
        il.MarkLabel(familyKnown);
        var filterOrder = il.DefineLabel();
        var buildResult = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, family);
        il.Emit(OpCodes.Brfalse, filterOrder);
        il.Emit(OpCodes.Ldloc, family);
        il.Emit(OpCodes.Ldloc, addressFamily);
        il.Emit(OpCodes.Bne_Un, next);
        il.MarkLabel(filterOrder);
        il.Emit(OpCodes.Ldloc, preferredFamily);
        il.Emit(OpCodes.Brfalse, buildResult);
        il.Emit(OpCodes.Ldloc, preferredFamily);
        il.Emit(OpCodes.Ldloc, addressFamily);
        il.Emit(OpCodes.Ceq);
        il.Emit(OpCodes.Ldloc, pass);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Ceq);
        il.Emit(OpCodes.Bne_Un, next);
        il.MarkLabel(buildResult);
        il.Emit(OpCodes.Newobj, typeof(Dictionary<string, object>).GetConstructor(Type.EmptyTypes)!);
        il.Emit(OpCodes.Dup);
        il.Emit(OpCodes.Ldstr, "address");
        var formatAddress = il.DefineLabel();
        var addressTextReady = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, isLiteral);
        il.Emit(OpCodes.Brfalse, formatAddress);
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Br, addressTextReady);
        il.MarkLabel(formatAddress);
        il.Emit(OpCodes.Ldloc, address);
        il.Emit(OpCodes.Callvirt, typeof(IPAddress).GetMethod("ToString", Type.EmptyTypes)!);
        il.MarkLabel(addressTextReady);
        var add = typeof(Dictionary<string, object>).GetMethod("Add")!;
        il.Emit(OpCodes.Callvirt, add);
        il.Emit(OpCodes.Dup);
        il.Emit(OpCodes.Ldstr, "family");
        il.Emit(OpCodes.Ldloc, addressFamily);
        il.Emit(OpCodes.Conv_R8);
        il.Emit(OpCodes.Box, typeof(double));
        il.Emit(OpCodes.Callvirt, add);
        il.Emit(OpCodes.Call, runtime.ObjectConstruction.Create);
        il.Emit(OpCodes.Stloc, result);
        var addResult = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, all);
        il.Emit(OpCodes.Brtrue, addResult);
        il.Emit(OpCodes.Leave, done);
        il.MarkLabel(addResult);
        il.Emit(OpCodes.Ldloc, results);
        il.Emit(OpCodes.Ldloc, result);
        il.Emit(OpCodes.Callvirt, typeof(List<object>).GetMethod("Add")!);
        il.MarkLabel(next);
        il.Emit(OpCodes.Ldloc, index);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Add);
        il.Emit(OpCodes.Stloc, index);
        il.Emit(OpCodes.Br, loop);
        il.MarkLabel(passDone);
        var finish = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, preferredFamily);
        il.Emit(OpCodes.Brfalse, finish);
        il.Emit(OpCodes.Ldloc, pass);
        il.Emit(OpCodes.Brtrue, finish);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Stloc, pass);
        il.Emit(OpCodes.Br, passStart);
        il.MarkLabel(finish);
        var notFound = il.DefineLabel();
        il.Emit(OpCodes.Ldloc, all);
        il.Emit(OpCodes.Brfalse, notFound);
        il.Emit(OpCodes.Ldloc, results);
        il.Emit(OpCodes.Callvirt, typeof(List<object>).GetProperty("Count")!.GetMethod!);
        il.Emit(OpCodes.Brfalse, notFound);
        il.Emit(OpCodes.Ldloc, results);
        il.Emit(OpCodes.Callvirt, typeof(List<object>).GetMethod("ToArray")!);
        il.Emit(OpCodes.Call, runtime.ArrayOperations.Create);
        il.Emit(OpCodes.Stloc, result);
        il.Emit(OpCodes.Leave, done);
        il.MarkLabel(notFound);
        il.Emit(OpCodes.Ldc_I4, (int)SocketError.HostNotFound);
        il.Emit(OpCodes.Newobj, typeof(SocketException).GetConstructor([typeof(int)])!);
        il.Emit(OpCodes.Throw);
        il.BeginCatchBlock(typeof(SocketException));
        il.Emit(OpCodes.Pop);
        il.Emit(OpCodes.Ldstr, "Runtime Error: dns.lookup ENOTFOUND ");
        il.Emit(OpCodes.Ldloc, hostname);
        il.Emit(OpCodes.Call, typeof(string).GetMethod("Concat", [typeof(string), typeof(string)])!);
        il.Emit(OpCodes.Newobj, typeof(Exception).GetConstructor([typeof(string)])!);
        il.Emit(OpCodes.Throw);
        il.EndExceptionBlock();
        il.MarkLabel(done);
        il.Emit(OpCodes.Ldloc, result);
        il.Emit(OpCodes.Ret);
    }
}
