using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

if (args is ["--self-test"])
{
    try
    {
        DuplicateCheck.SelfTest();
        EmitterDeadCodeCheck.SelfTest();
        return 0;
    }
    catch (Exception exception)
    {
        Console.Error.WriteLine(exception.Message);
        return 1;
    }
}
if (args.Length != 1 && args is not [_, "--inventory"])
{
    Console.Error.WriteLine("Usage: CodeQuality <repository-root> [--inventory] | --self-test");
    return 2;
}
try
{
    var root = Path.GetFullPath(args[0]);
    var groups = DuplicateCheck.Scan(Path.Combine(root, "src"), root);
    if (args is [_, "--inventory"])
    {
        Console.WriteLine(JsonSerializer.Serialize(groups.Select(g => new AcceptedDuplicate(g.Hash,
            g.Occurrences.Select(o => o.Member).ToArray(), "")), new JsonSerializerOptions { WriteIndented = true }));
        return 0;
    }
    var baselinePath = Path.Combine(root, "eng", "CodeQuality", "duplicates.json");
    var baseline = JsonSerializer.Deserialize<AcceptedDuplicate[]>(File.ReadAllText(baselinePath))
        ?? throw new InvalidDataException("Empty duplicate baseline.");
    var errors = DuplicateCheck.Compare(groups, baseline);
    errors.AddRange(EmitterDeadCodeCheck.Scan(Path.Combine(root, "src", "SharpTS", "Compilation")));
    foreach (var error in errors) Console.Error.WriteLine(error);
    Console.WriteLine($"Code quality: {groups.Length} duplicate groups (>=60 tokens), {errors.Count} errors.");
    return errors.Count == 0 ? 0 : 1;
}
catch (Exception exception)
{
    Console.Error.WriteLine($"Code quality check failed: {exception.Message}");
    return 2;
}

internal sealed record Occurrence(string Member, int Line);
internal sealed record Duplicate(string Hash, Occurrence[] Occurrences);
internal sealed record AcceptedDuplicate(string Hash, string[] Members, string Reason);

internal static class DuplicateCheck
{
    private static string SignatureText(SyntaxNode? node) => node == null ? "" :
        node.ReplaceTrivia(node.DescendantTrivia(), (_, _) => default).WithoutTrivia().NormalizeWhitespace().ToFullString();

    internal static bool GeneratedMember(MethodDeclarationSyntax method) => method.AncestorsAndSelf()
        .OfType<MemberDeclarationSyntax>().SelectMany(m => m.AttributeLists).SelectMany(a => a.Attributes)
        .Any(a => a.Name.ToString() is "GeneratedCode" or "GeneratedCodeAttribute" or
            "System.CodeDom.Compiler.GeneratedCode" or "System.CodeDom.Compiler.GeneratedCodeAttribute");

    internal static bool Excluded(string path, string text) =>
        path.Split('/').Any(part => part is "bin" or "obj" or "Templates") ||
        path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
        path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
        text.TrimStart().StartsWith("// <auto-generated", StringComparison.OrdinalIgnoreCase);

    internal static Duplicate[] Scan(string directory, string root)
    {
        var members = new List<(string Hash, Occurrence Occurrence)>();
        foreach (var file in Directory.EnumerateFiles(directory, "*.cs", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
        {
            var path = Path.GetRelativePath(root, file).Replace('\\', '/');
            var text = File.ReadAllText(file);
            if (Excluded(path, text)) continue;
            var tree = CSharpSyntaxTree.ParseText(text, new CSharpParseOptions(LanguageVersion.Preview), path);
            var errors = tree.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
            if (errors.Length != 0) throw new InvalidDataException(string.Join(Environment.NewLine, errors.Select(d => d.ToString())));
            foreach (var method in tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>())
            {
                SyntaxNode? body = (SyntaxNode?)method.Body ?? method.ExpressionBody;
                if (body == null || GeneratedMember(method)) continue;
                var tokens = body.DescendantTokens().ToArray();
                if (tokens.Length < 60) continue;
                // Preserve token kind, identifiers and literal spelling; ignore only trivia.
                var canonical = string.Concat(tokens.Select(t => $"{t.RawKind}:{t.Text.Length}:{t.Text};"));
                var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical))).ToLowerInvariant();
                var type = string.Join(".", method.Ancestors().OfType<TypeDeclarationSyntax>().Reverse().Select(t => t.Identifier.Text + SignatureText(t.TypeParameterList)));
                var signature = method.Identifier.Text + SignatureText(method.TypeParameterList) + SignatureText(method.ParameterList);
                members.Add((hash, new Occurrence($"{path}::{type}.{signature}", method.GetLocation().GetLineSpan().StartLinePosition.Line + 1)));
            }
        }
        return members.GroupBy(m => m.Hash).Where(g => g.Count() > 1)
            .Select(g => new Duplicate(g.Key, g.Select(m => m.Occurrence).OrderBy(o => o.Member, StringComparer.Ordinal).ToArray()))
            .OrderBy(g => g.Hash, StringComparer.Ordinal).ToArray();
    }

    internal static List<string> Compare(Duplicate[] actual, AcceptedDuplicate[] baseline)
    {
        var errors = new List<string>();
        if (baseline.Select(b => b.Hash).Distinct().Count() != baseline.Length)
            errors.Add("Duplicate hashes in baseline.");
        foreach (var entry in baseline)
            if (string.IsNullOrWhiteSpace(entry.Reason) || entry.Members.Length < 2 || entry.Members.Distinct().Count() != entry.Members.Length)
                errors.Add($"Invalid baseline entry {entry.Hash}: require a reason and distinct members.");
        foreach (var group in actual)
        {
            var accepted = baseline.FirstOrDefault(b => b.Hash == group.Hash);
            foreach (var occurrence in group.Occurrences)
                if (accepted == null || !accepted.Members.Contains(occurrence.Member, StringComparer.Ordinal))
                    errors.Add($"DUP001 {occurrence.Member} (line {occurrence.Line}): unapproved duplicate {group.Hash}. Extract shared code or review an exact baseline exception. Peers: {string.Join(", ", group.Occurrences.Select(o => o.Member))}");
        }
        foreach (var entry in baseline)
            foreach (var member in entry.Members)
                if (!actual.Any(g => g.Hash == entry.Hash && g.Occurrences.Any(o => o.Member == member)))
                    errors.Add($"Stale duplicate baseline: {entry.Hash} {member}. Remove or review the changed exception.");
        return errors;
    }

    internal static void SelfTest()
    {
        var root = Path.Combine(Path.GetTempPath(), "sharpts-duplicates-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            var body = "{ int sum = 0; " + string.Concat(Enumerable.Range(0, 15).Select(i => $"sum += {i}; ")) + "return sum; }";
            File.WriteAllText(Path.Combine(root, "A.cs"), $"class A {{ public int One() {body} }}");
            File.WriteAllText(Path.Combine(root, "B.cs"), $"class B {{ public int Two() {body.Replace(";", "; /* trivia */\n")} }}");
            var groups = Scan(root, root);
            Require(groups.Length == 1, "trivia-insensitive duplicate detection");
            Require(Compare(groups, []).Count == 2, "new duplicates fail");
            var baseline = new[] { new AcceptedDuplicate(groups[0].Hash, groups[0].Occurrences.Select(o => o.Member).ToArray(), "Fixture") };
            Require(Compare(groups, baseline).Count == 0, "reviewed duplicates pass");
            File.WriteAllText(Path.Combine(root, "A.cs"), $"class A {{ public int One(/* signature trivia */) {body} }}");
            Require(Compare(Scan(root, root), baseline).Count == 0, "signature comments do not invalidate baseline");
            File.WriteAllText(Path.Combine(root, "C.cs"), $"class C {{ public int Three() {body} }}");
            Require(Compare(Scan(root, root), baseline).Count == 1, "third copy of accepted body fails");
            File.WriteAllText(Path.Combine(root, "C.cs"), "// <auto-generated/>\n" + $"class C {{ public int Three() {body} }}");
            Require(Compare(Scan(root, root), baseline).Count == 0, "generated file excluded");
            File.WriteAllText(Path.Combine(root, "B.cs"), $"class B {{ public int Two() {body.Replace("+= 14", "+= 99")} }}");
            Require(Scan(root, root).Length == 0, "literal changes matter");
            Require(Compare(Scan(root, root), baseline).Count == 2, "stale exceptions fail");
            Require(Excluded("src/App/obj/Debug/Generated.cs", "") && Excluded("src/Sdk/Templates/App.cs", ""), "build output and template exclusions");
            File.WriteAllText(Path.Combine(root, "Broken.cs"), "class {");
            try { Scan(root, root); throw new Exception("Invalid syntax passed."); }
            catch (InvalidDataException) { }
            Console.WriteLine("Duplicate check self-tests passed.");
        }
        finally { Directory.Delete(root, recursive: true); }
    }

    private static void Require(bool condition, string description)
    {
        if (!condition) throw new InvalidOperationException($"Self-test failed: {description}");
    }
}
