// <auto-generated />
import type { CommonProps, GuiChild, GuiElement, TextualChild, ControlRef, WindowHandle, StackPanelHandle, GridHandle, BorderHandle, TextBlockHandle, ButtonHandle, TextBoxHandle, Thickness, HorizontalAlignment, VerticalAlignment, Orientation, ScrollBarVisibility, Theme, Stretch, SelectionMode, Dock, FontWeight, TextAlignment, ContentStyleProps, TextStyleProps, RichTextRun, DrawingCommand } from "./runtime-types";
/** @internal */
export const descriptorSchemaVersion = 1;
/** @internal */
export const descriptorSchemaHash = "1e7a4cdd01065d70da9be0d4953d54954ba969aaca5daec7b961239dabd48bc5";
/** @internal */
export interface ChildrenProps { children?: GuiChild; }
/** @internal */
export interface TextualChildrenProps { children?: TextualChild; }
/** @internal */
export interface SingleElementChildProps { children?: GuiElement | null | undefined; }
/** Properties accepted by the Window component.
 * @category Components
 */
export interface WindowProps extends CommonProps<WindowHandle>, SingleElementChildProps {
    /** Text displayed in the window title bar. */
    title?: string;
    /** Whether the user can resize the window. */
    canResize?: boolean;
    /** Whether the window remains above non-topmost windows. */
    topmost?: boolean;
    /** Light, dark, or operating-system window theme. */
    theme?: Theme;
}
/** Properties accepted by the StackPanel component.
 * @category Components
 */
export interface StackPanelProps extends CommonProps<StackPanelHandle>, ChildrenProps {
    /** Distance between adjacent child controls. */
    spacing?: number;
    /** Direction in which child controls are arranged. */
    orientation?: Orientation;
}
/** Properties accepted by the WrapPanel component.
 * @category Components
 */
export interface WrapPanelProps extends CommonProps<unknown>, ChildrenProps {
    /** Distance between adjacent child controls. */
    spacing?: number;
    /** Direction in which child controls are arranged. */
    orientation?: Orientation;
}
/** Properties accepted by the DockPanel component.
 * @category Components
 */
export interface DockPanelProps extends CommonProps<unknown>, ChildrenProps {
    /** Whether the last DockPanel child fills the remaining space. */
    lastChildFill?: boolean;
}
/** Properties accepted by the Grid component.
 * @category Components
 */
export interface GridProps extends CommonProps<GridHandle>, ChildrenProps {
    /** Comma-separated Avalonia grid row definitions. */
    rows?: string;
    /** Comma-separated Avalonia grid column definitions. */
    columns?: string;
}
/** Properties accepted by the Border component.
 * @category Components
 */
export interface BorderProps extends CommonProps<BorderHandle>, SingleElementChildProps {
    /** Space between the control border and its content. */
    padding?: Thickness;
    /** Background brush or color value. */
    background?: string;
    /** Brush or color used to draw the border. */
    borderBrush?: string;
    /** Thickness of the border around the control. */
    borderThickness?: Thickness;
    /** Radius applied to the control corners. */
    cornerRadius?: number;
}
/** Properties accepted by the ScrollViewer component.
 * @category Components
 */
export interface ScrollViewerProps extends CommonProps<unknown>, SingleElementChildProps {
    /** Visibility policy for the horizontal scroll bar. */
    horizontalScrollBarVisibility?: ScrollBarVisibility;
    /** Visibility policy for the vertical scroll bar. */
    verticalScrollBarVisibility?: ScrollBarVisibility;
}
/** Properties accepted by the TextBlock component.
 * @category Components
 */
export interface TextBlockProps extends CommonProps<TextBlockHandle>, TextualChildrenProps, TextStyleProps {
    /** Whether text wraps when it exceeds the available width. */
    textWrapping?: "noWrap" | "wrap";
}
/** Properties accepted by the Button component.
 * @category Components
 */
export interface ButtonProps extends CommonProps<ButtonHandle>, TextualChildrenProps, ContentStyleProps {
    /** Called when the control is activated. */
    onClick?: () => void;
}
/** Properties accepted by the TextBox component.
 * @category Components
 */
export interface TextBoxProps extends CommonProps<TextBoxHandle>, ContentStyleProps {
    /** Text value displayed or edited by the control. */
    text?: string;
    /** Hint displayed when the input contains no value. */
    placeholder?: string;
    /** Whether the text value can be selected but not edited. */
    isReadOnly?: boolean;
    /** Whether the text box accepts the Return key as a line break. */
    acceptsReturn?: boolean;
    /** Maximum number of characters accepted by the text input. */
    maxLength?: number;
    /** Called after the editable text changes. */
    onTextChanged?: (value: string) => void;
}
/** Properties accepted by the PasswordBox component.
 * @category Components
 */
export interface PasswordBoxProps extends CommonProps<TextBoxHandle>, ContentStyleProps {
    /** Current value of the control. */
    value?: string;
    /** Hint displayed when the input contains no value. */
    placeholder?: string;
    /** Whether password characters are displayed instead of masked. */
    revealPassword?: boolean;
    /** Maximum number of characters accepted by the text input. */
    maxLength?: number;
    /** Called after the control value changes. */
    onValueChanged?: (value: string) => void;
}
/** Properties accepted by the CheckBox component.
 * @category Components
 */
export interface CheckBoxProps extends CommonProps<unknown>, TextualChildrenProps, ContentStyleProps {
    /** Whether the toggle control is checked. */
    isChecked?: boolean;
    /** Called after the checked state changes. */
    onCheckedChanged?: (value: boolean) => void;
}
/** Properties accepted by the RadioButton component.
 * @category Components
 */
export interface RadioButtonProps extends CommonProps<unknown>, TextualChildrenProps, ContentStyleProps {
    /** Name that groups mutually exclusive radio buttons. */
    groupName: string;
    /** Whether the toggle control is checked. */
    isChecked?: boolean;
    /** Called after the checked state changes. */
    onCheckedChanged?: (value: boolean) => void;
}
/** Properties accepted by the ToggleSwitch component.
 * @category Components
 */
export interface ToggleSwitchProps extends CommonProps<unknown>, TextualChildrenProps, ContentStyleProps {
    /** Whether the toggle control is checked. */
    isChecked?: boolean;
    /** Called after the checked state changes. */
    onCheckedChanged?: (value: boolean) => void;
}
/** Properties accepted by the ComboBox component.
 * @category Components
 */
export interface ComboBoxProps extends CommonProps<unknown>, ContentStyleProps {
    /** Items displayed by the control. */
    items: readonly string[];
    /** Zero-based selected item index, or -1 when no item is selected. */
    selectedIndex?: number;
    /** Called after the selected item or items change. */
    onSelectionChanged?: (index: number) => void;
}
/** Properties accepted by the ListBox component.
 * @category Components
 */
export interface ListBoxProps extends CommonProps<unknown>, ContentStyleProps {
    /** Items displayed by the control. */
    items: readonly string[];
    /** Zero-based indices of the selected items. */
    selectedIndices?: readonly number[];
    /** Whether one or multiple items can be selected. */
    selectionMode?: SelectionMode;
    /** Called after the selected item or items change. */
    onSelectionChanged?: (indices: number[]) => void;
}
/** Properties accepted by the ItemsControl component.
 * @category Components
 */
export interface ItemsControlProps extends CommonProps<unknown>, ChildrenProps {
}
/** Properties accepted by the VirtualizingList component.
 * @category Components
 */
export interface VirtualizingListProps extends CommonProps<unknown>, ChildrenProps {
    /** Zero-based indices of the selected items. */
    selectedIndices?: readonly number[];
    /** Whether one or multiple items can be selected. */
    selectionMode?: SelectionMode;
    /** Called after the selected item or items change. */
    onSelectionChanged?: (indices: number[]) => void;
}
/** Properties accepted by the TreeView component.
 * @category Components
 */
export interface TreeViewProps extends CommonProps<unknown>, ChildrenProps {
}
/** Properties accepted by the TreeViewItem component.
 * @category Components
 */
export interface TreeViewItemProps extends CommonProps<unknown>, ChildrenProps {
    /** Text displayed as the item header. */
    header: string;
    /** Whether the tree item is expanded. */
    isExpanded?: boolean;
    /** Called after the expanded state changes. */
    onExpandedChanged?: (expanded: boolean) => void;
}
/** Properties accepted by the Canvas component.
 * @category Components
 */
export interface CanvasProps extends CommonProps<unknown>, ChildrenProps {
}
/** Properties accepted by the RichTextBlock component.
 * @category Components
 */
export interface RichTextBlockProps extends CommonProps<TextBlockHandle> {
    /** Independently formatted text runs rendered by the control. */
    runs: readonly RichTextRun[];
}
/** Properties accepted by the DrawingCanvas component.
 * @category Components
 */
export interface DrawingCanvasProps extends CommonProps<unknown> {
    /** Retained drawing commands rendered by the canvas. */
    commands: readonly DrawingCommand[];
}
/** Properties accepted by the NumericUpDown component.
 * @category Components
 */
export interface NumericUpDownProps extends CommonProps<unknown>, ContentStyleProps {
    /** Minimum value accepted by the control. */
    minimum?: number;
    /** Maximum value accepted by the control. */
    maximum?: number;
    /** Step applied when the numeric value is increased or decreased. */
    increment?: number;
    /** Current value of the control. */
    value?: number | null;
    /** Called after the control value changes. */
    onValueChanged?: (value: number | null) => void;
}
/** Properties accepted by the DatePicker component.
 * @category Components
 */
export interface DatePickerProps extends CommonProps<unknown> {
    /** Current value of the control. */
    value?: string | null;
    /** Called after the control value changes. */
    onValueChanged?: (value: string | null) => void;
}
/** Properties accepted by the TimePicker component.
 * @category Components
 */
export interface TimePickerProps extends CommonProps<unknown> {
    /** Current value of the control. */
    value?: string | null;
    /** Called after the control value changes. */
    onValueChanged?: (value: string | null) => void;
}
/** Properties accepted by the Slider component.
 * @category Components
 */
export interface SliderProps extends CommonProps<unknown> {
    /** Minimum value accepted by the control. */
    minimum?: number;
    /** Maximum value accepted by the control. */
    maximum?: number;
    /** Current value of the control. */
    value?: number;
    /** Called after the control value changes. */
    onValueChanged?: (value: number) => void;
}
/** Properties accepted by the ProgressBar component.
 * @category Components
 */
export interface ProgressBarProps extends CommonProps<unknown> {
    /** Minimum value accepted by the control. */
    minimum?: number;
    /** Maximum value accepted by the control. */
    maximum?: number;
    /** Current value of the control. */
    value?: number;
}
/** Properties accepted by the Separator component.
 * @category Components
 */
export interface SeparatorProps extends CommonProps<unknown> {
}
/** Properties accepted by the Image component.
 * @category Components
 */
export interface ImageProps extends CommonProps<unknown> {
    /** Application asset URI or path of the displayed image. */
    source: string;
    /** How the image is resized to fit its layout slot. */
    stretch?: Stretch;
    /** Called after the image loads successfully. */
    onLoad?: () => void;
    /** Called when the image cannot be loaded, with an error message. */
    onError?: (message: string) => void;
}
/** Properties accepted by the TabControl component.
 * @category Components
 */
export interface TabControlProps extends CommonProps<unknown>, ChildrenProps {
    /** Zero-based selected item index, or -1 when no item is selected. */
    selectedIndex?: number;
    /** Called after the selected item or items change. */
    onSelectionChanged?: (index: number) => void;
}
/** Properties accepted by the TabItem component.
 * @category Components
 */
export interface TabItemProps extends CommonProps<unknown>, SingleElementChildProps {
    /** Text displayed as the item header. */
    header: string;
}
/** Properties accepted by the Menu component.
 * @category Components
 */
export interface MenuProps extends CommonProps<unknown>, ChildrenProps {
}
/** Properties accepted by the MenuItem component.
 * @category Components
 */
export interface MenuItemProps extends CommonProps<unknown>, ChildrenProps {
    /** Text displayed as the item header. */
    header: string;
    /** Whether the toggle control is checked. */
    isChecked?: boolean;
    /** Called when the control is activated. */
    onClick?: () => void;
}
/** @internal */
type DesktopTag<TProps> = (props: TProps) => GuiElement;
/** @internal */
function tag<TProps>(name: string): DesktopTag<TProps> { return name as any; }
/** Top-level desktop window.
 * @category Components
 * @function
 */
export const Window = tag<WindowProps>("Window");
/** Lays out children in one row or column.
 * @category Components
 * @function
 */
export const StackPanel = tag<StackPanelProps>("StackPanel");
/** Horizontal command container.
 * @category Components
 * @function
 */
export const ToolBar = tag<StackPanelProps>("ToolBar");
/** Wraps children across available space.
 * @category Components
 * @function
 */
export const WrapPanel = tag<WrapPanelProps>("WrapPanel");
/** Docks children to container edges.
 * @category Components
 * @function
 */
export const DockPanel = tag<DockPanelProps>("DockPanel");
/** Grid layout using Avalonia row and column syntax.
 * @category Components
 * @function
 */
export const Grid = tag<GridProps>("Grid");
/** Decorates one child with background and border.
 * @category Components
 * @function
 */
export const Border = tag<BorderProps>("Border");
/** Status container backed by a Border.
 * @category Components
 * @function
 */
export const StatusBar = tag<BorderProps>("StatusBar");
/** Scrollable single-child viewport.
 * @category Components
 * @function
 */
export const ScrollViewer = tag<ScrollViewerProps>("ScrollViewer");
/** Displays textual children.
 * @category Components
 * @function
 */
export const TextBlock = tag<TextBlockProps>("TextBlock");
/** Clickable textual button.
 * @category Components
 * @function
 */
export const Button = tag<ButtonProps>("Button");
/** Editable text input.
 * @category Components
 * @function
 */
export const TextBox = tag<TextBoxProps>("TextBox");
/** Masked text input.
 * @category Components
 * @function
 */
export const PasswordBox = tag<PasswordBoxProps>("PasswordBox");
/** Boolean toggle with a textual label.
 * @category Components
 * @function
 */
export const CheckBox = tag<CheckBoxProps>("CheckBox");
/** Mutually exclusive grouped toggle.
 * @category Components
 * @function
 */
export const RadioButton = tag<RadioButtonProps>("RadioButton");
/** Switch-style boolean toggle.
 * @category Components
 * @function
 */
export const ToggleSwitch = tag<ToggleSwitchProps>("ToggleSwitch");
/** Single-selection drop-down list.
 * @category Components
 * @function
 */
export const ComboBox = tag<ComboBoxProps>("ComboBox");
/** Single- or multiple-selection list.
 * @category Components
 * @function
 */
export const ListBox = tag<ListBoxProps>("ListBox");
/** Native items host for keyed templated children.
 * @category Components
 * @function
 */
export const ItemsControl = tag<ItemsControlProps>("ItemsControl");
/** Virtualizing native list whose keyed children are produced by a typed item template.
 * @category Components
 * @function
 */
export const VirtualizingList = tag<VirtualizingListProps>("VirtualizingList");
/** Hierarchical native tree host.
 * @category Components
 * @function
 */
export const TreeView = tag<TreeViewProps>("TreeView");
/** One expandable native tree node.
 * @category Components
 * @function
 */
export const TreeViewItem = tag<TreeViewItemProps>("TreeViewItem");
/** Absolute-positioned child canvas.
 * @category Components
 * @function
 */
export const Canvas = tag<CanvasProps>("Canvas");
/** TextBlock with independently formatted inline runs.
 * @category Components
 * @function
 */
export const RichTextBlock = tag<RichTextBlockProps>("RichTextBlock");
/** Retained vector drawing surface for lines, rectangles, and ellipses.
 * @category Components
 * @function
 */
export const DrawingCanvas = tag<DrawingCanvasProps>("DrawingCanvas");
/** Numeric spinner input.
 * @category Components
 * @function
 */
export const NumericUpDown = tag<NumericUpDownProps>("NumericUpDown");
/** ISO date picker.
 * @category Components
 * @function
 */
export const DatePicker = tag<DatePickerProps>("DatePicker");
/** Time picker.
 * @category Components
 * @function
 */
export const TimePicker = tag<TimePickerProps>("TimePicker");
/** Continuous range input.
 * @category Components
 * @function
 */
export const Slider = tag<SliderProps>("Slider");
/** Read-only range progress display.
 * @category Components
 * @function
 */
export const ProgressBar = tag<ProgressBarProps>("ProgressBar");
/** Visual separator.
 * @category Components
 * @function
 */
export const Separator = tag<SeparatorProps>("Separator");
/** Displays an application image asset.
 * @category Components
 * @function
 */
export const Image = tag<ImageProps>("Image");
/** Tabbed page selector.
 * @category Components
 * @function
 */
export const TabControl = tag<TabControlProps>("TabControl");
/** One tab page.
 * @category Components
 * @function
 */
export const TabItem = tag<TabItemProps>("TabItem");
/** Menu item container.
 * @category Components
 * @function
 */
export const Menu = tag<MenuProps>("Menu");
/** Menu command or submenu.
 * @category Components
 * @function
 */
export const MenuItem = tag<MenuItemProps>("MenuItem");
/** @internal */
export const controlContract = [
  { kind: "Window", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "title", "canResize", "topmost", "theme"] },
  { kind: "StackPanel", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "spacing", "orientation"] },
  { kind: "ToolBar", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "spacing", "orientation"] },
  { kind: "WrapPanel", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "spacing", "orientation"] },
  { kind: "DockPanel", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "lastChildFill"] },
  { kind: "Grid", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "rows", "columns"] },
  { kind: "Border", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "padding", "background", "borderBrush", "borderThickness", "cornerRadius"] },
  { kind: "StatusBar", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "padding", "background", "borderBrush", "borderThickness", "cornerRadius"] },
  { kind: "ScrollViewer", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "horizontalScrollBarVisibility", "verticalScrollBarVisibility"] },
  { kind: "TextBlock", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "textWrapping"] },
  { kind: "Button", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "onClick"] },
  { kind: "TextBox", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "text", "placeholder", "isReadOnly", "acceptsReturn", "maxLength", "onTextChanged"] },
  { kind: "PasswordBox", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "value", "placeholder", "revealPassword", "maxLength", "onValueChanged"] },
  { kind: "CheckBox", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "isChecked", "onCheckedChanged"] },
  { kind: "RadioButton", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "groupName", "isChecked", "onCheckedChanged"] },
  { kind: "ToggleSwitch", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "isChecked", "onCheckedChanged"] },
  { kind: "ComboBox", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "items", "selectedIndex", "onSelectionChanged"] },
  { kind: "ListBox", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "items", "selectedIndices", "selectionMode", "onSelectionChanged"] },
  { kind: "ItemsControl", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop"] },
  { kind: "VirtualizingList", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "selectedIndices", "selectionMode", "onSelectionChanged"] },
  { kind: "TreeView", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop"] },
  { kind: "TreeViewItem", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "header", "isExpanded", "onExpandedChanged"] },
  { kind: "Canvas", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop"] },
  { kind: "RichTextBlock", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "runs"] },
  { kind: "DrawingCanvas", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "commands"] },
  { kind: "NumericUpDown", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "foreground", "fontFamily", "fontSize", "fontWeight", "fontStyle", "textAlignment", "background", "padding", "cornerRadius", "horizontalContentAlignment", "verticalContentAlignment", "minimum", "maximum", "increment", "value", "onValueChanged"] },
  { kind: "DatePicker", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "value", "onValueChanged"] },
  { kind: "TimePicker", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "value", "onValueChanged"] },
  { kind: "Slider", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "minimum", "maximum", "value", "onValueChanged"] },
  { kind: "ProgressBar", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "minimum", "maximum", "value"] },
  { kind: "Separator", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop"] },
  { kind: "Image", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "source", "stretch", "onLoad", "onError"] },
  { kind: "TabControl", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "selectedIndex", "onSelectionChanged"] },
  { kind: "TabItem", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "header"] },
  { kind: "Menu", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop"] },
  { kind: "MenuItem", props: ["ref", "width", "height", "minWidth", "minHeight", "maxWidth", "maxHeight", "margin", "horizontalAlignment", "verticalAlignment", "isVisible", "isEnabled", "opacity", "toolTip", "automationName", "classes", "canvasLeft", "canvasTop", "gridRow", "gridColumn", "gridRowSpan", "gridColumnSpan", "dock", "onKeyDown", "onKeyUp", "allowDrop", "onDragOver", "onDrop", "header", "isChecked", "onClick"] },
] as const;
