// <auto-generated />
// Generated from eng/GuiPreviewVersion.props by scripts/sync-gui-preview-version.ps1.
namespace SharpTS.Cli;

internal static class GuiPreviewVersion
{
    internal const string Value = "0.3.0-preview.1";
}
