// <auto-generated />
// Generated from eng/GuiVersion.props by scripts/sync-gui-version.ps1.
namespace SharpTS.Cli;

internal static class GuiVersion
{
    internal const string Value = "0.0.0-local";
}
