using System.Reflection;
using System.Reflection.Emit;

namespace SharpTS.Compilation;

/// <summary>
/// Holds references to runtime support types and methods emitted into compiled assemblies.
/// </summary>
/// <remarks>
/// Enables standalone DLLs without requiring SharpTS.dll at runtime. Contains references
/// to emitted types (TSFunction, TSRuntime) and helper methods (console.log, type coercion,
/// array/object operations, invocation helpers). These are generated by <see cref="RuntimeTypes"/>
/// and used by <see cref="ILEmitter"/> when emitting calls to runtime support code.
/// </remarks>
/// <seealso cref="RuntimeTypes"/>
/// <seealso cref="ILCompiler"/>
/// <seealso cref="ILEmitter"/>
public class EmittedRuntime
{
    // The emitted TSFunction class
    public TypeBuilder TSFunctionType { get; set; } = null!;
    public ConstructorBuilder TSFunctionCtor { get; set; } = null!;
    public MethodBuilder TSFunctionInvoke { get; set; } = null!;

    // The emitted runtime helper class
    public TypeBuilder RuntimeType { get; set; } = null!;

    // Console methods
    public MethodBuilder ConsoleLog { get; set; } = null!;
    public MethodBuilder ConsoleLogMultiple { get; set; } = null!;

    // Type coercion methods
    public MethodBuilder Stringify { get; set; } = null!;
    public MethodBuilder ToNumber { get; set; } = null!;
    public MethodBuilder IsTruthy { get; set; } = null!;
    public MethodBuilder TypeOf { get; set; } = null!;
    public MethodBuilder InstanceOf { get; set; } = null!;

    // Operator methods
    public MethodBuilder Add { get; set; } = null!;
    public new MethodBuilder Equals { get; set; } = null!;

    // Array methods
    public MethodBuilder CreateArray { get; set; } = null!;
    public MethodBuilder GetLength { get; set; } = null!;
    public MethodBuilder GetElement { get; set; } = null!;
    public MethodBuilder GetKeys { get; set; } = null!;
    public MethodBuilder GetValues { get; set; } = null!;
    public MethodBuilder GetEntries { get; set; } = null!;
    public MethodBuilder IsArray { get; set; } = null!;
    public MethodBuilder SpreadArray { get; set; } = null!;
    public MethodBuilder ConcatArrays { get; set; } = null!;
    public MethodBuilder ExpandCallArgs { get; set; } = null!;
    public MethodBuilder ArrayPop { get; set; } = null!;
    public MethodBuilder ArrayShift { get; set; } = null!;
    public MethodBuilder ArrayUnshift { get; set; } = null!;
    public MethodBuilder ArraySlice { get; set; } = null!;
    public MethodBuilder ArrayMap { get; set; } = null!;
    public MethodBuilder ArrayFilter { get; set; } = null!;
    public MethodBuilder ArrayForEach { get; set; } = null!;
    public MethodBuilder ArrayPush { get; set; } = null!;
    public MethodBuilder ArrayFind { get; set; } = null!;
    public MethodBuilder ArrayFindIndex { get; set; } = null!;
    public MethodBuilder ArraySome { get; set; } = null!;
    public MethodBuilder ArrayEvery { get; set; } = null!;
    public MethodBuilder ArrayReduce { get; set; } = null!;
    public MethodBuilder ArrayIncludes { get; set; } = null!;
    public MethodBuilder ArrayIndexOf { get; set; } = null!;
    public MethodBuilder ArrayJoin { get; set; } = null!;
    public MethodBuilder ArrayConcat { get; set; } = null!;
    public MethodBuilder ArrayReverse { get; set; } = null!;

    // String methods
    public MethodBuilder StringCharAt { get; set; } = null!;
    public MethodBuilder StringSubstring { get; set; } = null!;
    public MethodBuilder StringIndexOf { get; set; } = null!;
    public MethodBuilder StringToUpperCase { get; set; } = null!;
    public MethodBuilder StringToLowerCase { get; set; } = null!;
    public MethodBuilder StringTrim { get; set; } = null!;
    public MethodBuilder StringReplace { get; set; } = null!;
    public MethodBuilder StringSplit { get; set; } = null!;
    public MethodBuilder StringIncludes { get; set; } = null!;
    public MethodBuilder StringStartsWith { get; set; } = null!;
    public MethodBuilder StringEndsWith { get; set; } = null!;
    public MethodBuilder StringSlice { get; set; } = null!;
    public MethodBuilder StringRepeat { get; set; } = null!;
    public MethodBuilder StringPadStart { get; set; } = null!;
    public MethodBuilder StringPadEnd { get; set; } = null!;
    public MethodBuilder StringCharCodeAt { get; set; } = null!;
    public MethodBuilder StringConcat { get; set; } = null!;
    public MethodBuilder StringLastIndexOf { get; set; } = null!;
    public MethodBuilder StringTrimStart { get; set; } = null!;
    public MethodBuilder StringTrimEnd { get; set; } = null!;
    public MethodBuilder StringReplaceAll { get; set; } = null!;
    public MethodBuilder StringAt { get; set; } = null!;

    // Object methods
    public MethodBuilder CreateObject { get; set; } = null!;
    public MethodBuilder GetProperty { get; set; } = null!;
    public MethodBuilder SetProperty { get; set; } = null!;
    public MethodBuilder GetFieldsProperty { get; set; } = null!;
    public MethodBuilder SetFieldsProperty { get; set; } = null!;
    public MethodBuilder GetArrayMethod { get; set; } = null!;
    public MethodBuilder MergeIntoObject { get; set; } = null!;
    public MethodBuilder GetIndex { get; set; } = null!;
    public MethodBuilder SetIndex { get; set; } = null!;

    // Invocation methods
    public MethodBuilder InvokeValue { get; set; } = null!;
    public MethodBuilder GetSuperMethod { get; set; } = null!;

    // Exception methods
    public MethodBuilder CreateException { get; set; } = null!;
    public MethodBuilder WrapException { get; set; } = null!;

    // Utility methods
    public MethodBuilder Random { get; set; } = null!;
    public MethodBuilder GetEnumMemberName { get; set; } = null!;
    public MethodBuilder ConcatTemplate { get; set; } = null!;
    public MethodBuilder ObjectRest { get; set; } = null!;

    // JSON methods
    public MethodBuilder JsonParse { get; set; } = null!;
    public MethodBuilder JsonParseWithReviver { get; set; } = null!;
    public MethodBuilder JsonStringify { get; set; } = null!;
    public MethodBuilder JsonStringifyFull { get; set; } = null!;

    // Symbol support
    public TypeBuilder TSSymbolType { get; set; } = null!;
    public ConstructorBuilder TSSymbolCtor { get; set; } = null!;
    public MethodBuilder CreateSymbol { get; set; } = null!;

    // Symbol storage for compiled objects (symbol as object key)
    public FieldBuilder SymbolStorageField { get; set; } = null!;
    public MethodBuilder GetSymbolDictMethod { get; set; } = null!;
    public MethodBuilder IsSymbolMethod { get; set; } = null!;

    // BigInt support
    public MethodBuilder CreateBigInt { get; set; } = null!;
    public MethodBuilder BigIntAdd { get; set; } = null!;
    public MethodBuilder BigIntSubtract { get; set; } = null!;
    public MethodBuilder BigIntMultiply { get; set; } = null!;
    public MethodBuilder BigIntDivide { get; set; } = null!;
    public MethodBuilder BigIntRemainder { get; set; } = null!;
    public MethodBuilder BigIntPow { get; set; } = null!;
    public MethodBuilder BigIntNegate { get; set; } = null!;
    public MethodBuilder BigIntBitwiseAnd { get; set; } = null!;
    public MethodBuilder BigIntBitwiseOr { get; set; } = null!;
    public MethodBuilder BigIntBitwiseXor { get; set; } = null!;
    public MethodBuilder BigIntBitwiseNot { get; set; } = null!;
    public MethodBuilder BigIntLeftShift { get; set; } = null!;
    public MethodBuilder BigIntRightShift { get; set; } = null!;
    public MethodBuilder BigIntEquals { get; set; } = null!;
    public MethodBuilder BigIntLessThan { get; set; } = null!;
    public MethodBuilder BigIntLessThanOrEqual { get; set; } = null!;
    public MethodBuilder BigIntGreaterThan { get; set; } = null!;
    public MethodBuilder BigIntGreaterThanOrEqual { get; set; } = null!;

    // Promise support
    public MethodBuilder PromiseResolve { get; set; } = null!;
    public MethodBuilder PromiseReject { get; set; } = null!;
    public MethodBuilder PromiseAll { get; set; } = null!;
    public MethodBuilder PromiseRace { get; set; } = null!;
    public MethodBuilder PromiseThen { get; set; } = null!;
    public MethodBuilder PromiseCatch { get; set; } = null!;
    public MethodBuilder PromiseFinally { get; set; } = null!;
    public MethodBuilder PromiseAllSettled { get; set; } = null!;
    public MethodBuilder PromiseAny { get; set; } = null!;

    // Number methods
    public MethodBuilder NumberParseInt { get; set; } = null!;
    public MethodBuilder NumberParseFloat { get; set; } = null!;
    public MethodBuilder NumberIsNaN { get; set; } = null!;
    public MethodBuilder NumberIsFinite { get; set; } = null!;
    public MethodBuilder NumberIsInteger { get; set; } = null!;
    public MethodBuilder NumberIsSafeInteger { get; set; } = null!;
    public MethodBuilder GlobalIsNaN { get; set; } = null!;
    public MethodBuilder GlobalIsFinite { get; set; } = null!;
    public MethodBuilder NumberToFixed { get; set; } = null!;
    public MethodBuilder NumberToPrecision { get; set; } = null!;
    public MethodBuilder NumberToExponential { get; set; } = null!;
    public MethodBuilder NumberToStringRadix { get; set; } = null!;
}
