using System.Reflection;
using System.Reflection.Emit;

namespace SharpTS.Compilation;

/// <summary>
/// Holds references to runtime support types and methods emitted into compiled assemblies.
/// </summary>
/// <remarks>
/// Enables standalone DLLs without requiring SharpTS.dll at runtime. Contains references
/// to emitted types (TSFunction, TSRuntime) and helper methods (console.log, type coercion,
/// array/object operations, invocation helpers). These are generated by <see cref="RuntimeTypes"/>
/// and used by <see cref="ILEmitter"/> when emitting calls to runtime support code.
/// </remarks>
/// <seealso cref="RuntimeTypes"/>
/// <seealso cref="ILCompiler"/>
/// <seealso cref="ILEmitter"/>
public class EmittedRuntime
{
    // The emitted TSFunction class
    public TypeBuilder TSFunctionType { get; set; } = null!;
    public ConstructorBuilder TSFunctionCtor { get; set; } = null!;
    public MethodBuilder TSFunctionInvoke { get; set; } = null!;
    public MethodBuilder TSFunctionInvokeWithThis { get; set; } = null!;
    public MethodBuilder TSFunctionBindThis { get; set; } = null!;

    // The emitted TSNamespace class
    public TypeBuilder TSNamespaceType { get; set; } = null!;
    public ConstructorBuilder TSNamespaceCtor { get; set; } = null!;
    public MethodBuilder TSNamespaceGet { get; set; } = null!;
    public MethodBuilder TSNamespaceSet { get; set; } = null!;

    // The emitted ReferenceEqualityComparer class (for Map/Set key equality)
    public TypeBuilder ReferenceEqualityComparerType { get; set; } = null!;
    public FieldBuilder ReferenceEqualityComparerInstance { get; set; } = null!;

    // The emitted runtime helper class
    public TypeBuilder RuntimeType { get; set; } = null!;

    // Console methods
    public MethodBuilder ConsoleLog { get; set; } = null!;
    public MethodBuilder ConsoleLogMultiple { get; set; } = null!;

    // Type coercion methods
    public MethodBuilder Stringify { get; set; } = null!;
    public MethodBuilder ToNumber { get; set; } = null!;
    public MethodBuilder IsTruthy { get; set; } = null!;
    public MethodBuilder TypeOf { get; set; } = null!;
    public MethodBuilder InstanceOf { get; set; } = null!;

    // Operator methods
    public MethodBuilder Add { get; set; } = null!;
    public new MethodBuilder Equals { get; set; } = null!;

    // Array methods
    public MethodBuilder CreateArray { get; set; } = null!;
    public MethodBuilder GetLength { get; set; } = null!;
    public MethodBuilder GetElement { get; set; } = null!;
    public MethodBuilder GetKeys { get; set; } = null!;
    public MethodBuilder GetValues { get; set; } = null!;
    public MethodBuilder GetEntries { get; set; } = null!;
    public MethodBuilder IsArray { get; set; } = null!;
    public MethodBuilder SpreadArray { get; set; } = null!;
    public MethodBuilder ConcatArrays { get; set; } = null!;
    public MethodBuilder ExpandCallArgs { get; set; } = null!;
    public MethodBuilder ArrayPop { get; set; } = null!;
    public MethodBuilder ArrayShift { get; set; } = null!;
    public MethodBuilder ArrayUnshift { get; set; } = null!;
    public MethodBuilder ArraySlice { get; set; } = null!;
    public MethodBuilder ArrayMap { get; set; } = null!;
    public MethodBuilder ArrayFilter { get; set; } = null!;
    public MethodBuilder ArrayForEach { get; set; } = null!;
    public MethodBuilder ArrayPush { get; set; } = null!;
    public MethodBuilder ArrayFind { get; set; } = null!;
    public MethodBuilder ArrayFindIndex { get; set; } = null!;
    public MethodBuilder ArraySome { get; set; } = null!;
    public MethodBuilder ArrayEvery { get; set; } = null!;
    public MethodBuilder ArrayReduce { get; set; } = null!;
    public MethodBuilder ArrayIncludes { get; set; } = null!;
    public MethodBuilder ArrayIndexOf { get; set; } = null!;
    public MethodBuilder ArrayJoin { get; set; } = null!;
    public MethodBuilder ArrayConcat { get; set; } = null!;
    public MethodBuilder ArrayReverse { get; set; } = null!;

    // String methods
    public MethodBuilder StringCharAt { get; set; } = null!;
    public MethodBuilder StringSubstring { get; set; } = null!;
    public MethodBuilder StringIndexOf { get; set; } = null!;
    public MethodBuilder StringToUpperCase { get; set; } = null!;
    public MethodBuilder StringToLowerCase { get; set; } = null!;
    public MethodBuilder StringTrim { get; set; } = null!;
    public MethodBuilder StringReplace { get; set; } = null!;
    public MethodBuilder StringSplit { get; set; } = null!;
    public MethodBuilder StringIncludes { get; set; } = null!;
    public MethodBuilder StringStartsWith { get; set; } = null!;
    public MethodBuilder StringEndsWith { get; set; } = null!;
    public MethodBuilder StringSlice { get; set; } = null!;
    public MethodBuilder StringRepeat { get; set; } = null!;
    public MethodBuilder StringPadStart { get; set; } = null!;
    public MethodBuilder StringPadEnd { get; set; } = null!;
    public MethodBuilder StringCharCodeAt { get; set; } = null!;
    public MethodBuilder StringConcat { get; set; } = null!;
    public MethodBuilder StringLastIndexOf { get; set; } = null!;
    public MethodBuilder StringTrimStart { get; set; } = null!;
    public MethodBuilder StringTrimEnd { get; set; } = null!;
    public MethodBuilder StringReplaceAll { get; set; } = null!;
    public MethodBuilder StringAt { get; set; } = null!;

    // Object methods
    public MethodBuilder CreateObject { get; set; } = null!;
    public MethodBuilder GetProperty { get; set; } = null!;
    public MethodBuilder SetProperty { get; set; } = null!;
    public MethodBuilder GetFieldsProperty { get; set; } = null!;
    public MethodBuilder SetFieldsProperty { get; set; } = null!;
    public MethodBuilder GetArrayMethod { get; set; } = null!;
    public MethodBuilder MergeIntoObject { get; set; } = null!;
    public MethodBuilder ToPascalCase { get; set; } = null!;
    public MethodBuilder GetIndex { get; set; } = null!;
    public MethodBuilder SetIndex { get; set; } = null!;

    // Invocation methods
    public MethodBuilder InvokeValue { get; set; } = null!;
    public MethodBuilder InvokeMethodValue { get; set; } = null!;
    public MethodBuilder GetSuperMethod { get; set; } = null!;

    // Exception methods
    public MethodBuilder CreateException { get; set; } = null!;
    public MethodBuilder WrapException { get; set; } = null!;

    // Utility methods
    public MethodBuilder Random { get; set; } = null!;
    public MethodBuilder GetEnumMemberName { get; set; } = null!;
    public MethodBuilder ConcatTemplate { get; set; } = null!;
    public MethodBuilder ObjectRest { get; set; } = null!;

    // JSON methods
    public MethodBuilder JsonParse { get; set; } = null!;
    public MethodBuilder JsonParseWithReviver { get; set; } = null!;
    public MethodBuilder JsonStringify { get; set; } = null!;
    public MethodBuilder JsonStringifyFull { get; set; } = null!;

    // Symbol support
    public TypeBuilder TSSymbolType { get; set; } = null!;
    public ConstructorBuilder TSSymbolCtor { get; set; } = null!;
    public MethodBuilder CreateSymbol { get; set; } = null!;

    // Well-known symbols (static fields on $TSSymbol)
    public FieldBuilder SymbolIterator { get; set; } = null!;
    public FieldBuilder SymbolAsyncIterator { get; set; } = null!;
    public FieldBuilder SymbolToStringTag { get; set; } = null!;
    public FieldBuilder SymbolHasInstance { get; set; } = null!;
    public FieldBuilder SymbolIsConcatSpreadable { get; set; } = null!;
    public FieldBuilder SymbolToPrimitive { get; set; } = null!;
    public FieldBuilder SymbolSpecies { get; set; } = null!;
    public FieldBuilder SymbolUnscopables { get; set; } = null!;

    // Symbol storage for compiled objects (symbol as object key)
    public FieldBuilder SymbolStorageField { get; set; } = null!;
    public MethodBuilder GetSymbolDictMethod { get; set; } = null!;
    public MethodBuilder IsSymbolMethod { get; set; } = null!;

    // BigInt support
    public MethodBuilder CreateBigInt { get; set; } = null!;
    public MethodBuilder BigIntAdd { get; set; } = null!;
    public MethodBuilder BigIntSubtract { get; set; } = null!;
    public MethodBuilder BigIntMultiply { get; set; } = null!;
    public MethodBuilder BigIntDivide { get; set; } = null!;
    public MethodBuilder BigIntRemainder { get; set; } = null!;
    public MethodBuilder BigIntPow { get; set; } = null!;
    public MethodBuilder BigIntNegate { get; set; } = null!;
    public MethodBuilder BigIntBitwiseAnd { get; set; } = null!;
    public MethodBuilder BigIntBitwiseOr { get; set; } = null!;
    public MethodBuilder BigIntBitwiseXor { get; set; } = null!;
    public MethodBuilder BigIntBitwiseNot { get; set; } = null!;
    public MethodBuilder BigIntLeftShift { get; set; } = null!;
    public MethodBuilder BigIntRightShift { get; set; } = null!;
    public MethodBuilder BigIntEquals { get; set; } = null!;
    public MethodBuilder BigIntLessThan { get; set; } = null!;
    public MethodBuilder BigIntLessThanOrEqual { get; set; } = null!;
    public MethodBuilder BigIntGreaterThan { get; set; } = null!;
    public MethodBuilder BigIntGreaterThanOrEqual { get; set; } = null!;

    // Promise support
    public MethodBuilder PromiseResolve { get; set; } = null!;
    public MethodBuilder PromiseReject { get; set; } = null!;
    public MethodBuilder PromiseAll { get; set; } = null!;
    public MethodBuilder PromiseRace { get; set; } = null!;
    public MethodBuilder PromiseThen { get; set; } = null!;
    public MethodBuilder PromiseCatch { get; set; } = null!;
    public MethodBuilder PromiseFinally { get; set; } = null!;
    public MethodBuilder PromiseAllSettled { get; set; } = null!;
    public MethodBuilder PromiseAny { get; set; } = null!;

    // Promise callback helpers (direct $TSFunction.Invoke without reflection)
    public MethodBuilder InvokeCallback { get; set; } = null!;
    public MethodBuilder InvokeCallbackNoArgs { get; set; } = null!;

    // PromiseAllSettled helper
    public MethodBuilder ProcessElementSettled { get; set; } = null!;

    // Number methods
    public MethodBuilder NumberParseInt { get; set; } = null!;
    public MethodBuilder NumberParseFloat { get; set; } = null!;
    public MethodBuilder NumberIsNaN { get; set; } = null!;
    public MethodBuilder NumberIsFinite { get; set; } = null!;
    public MethodBuilder NumberIsInteger { get; set; } = null!;
    public MethodBuilder NumberIsSafeInteger { get; set; } = null!;
    public MethodBuilder GlobalIsNaN { get; set; } = null!;
    public MethodBuilder GlobalIsFinite { get; set; } = null!;
    public MethodBuilder NumberToFixed { get; set; } = null!;
    public MethodBuilder NumberToPrecision { get; set; } = null!;
    public MethodBuilder NumberToExponential { get; set; } = null!;
    public MethodBuilder NumberToStringRadix { get; set; } = null!;

    // Map support
    public MethodBuilder CreateMap { get; set; } = null!;
    public MethodBuilder CreateMapFromEntries { get; set; } = null!;
    public MethodBuilder MapSize { get; set; } = null!;
    public MethodBuilder MapGet { get; set; } = null!;
    public MethodBuilder MapSet { get; set; } = null!;
    public MethodBuilder MapHas { get; set; } = null!;
    public MethodBuilder MapDelete { get; set; } = null!;
    public MethodBuilder MapClear { get; set; } = null!;
    public MethodBuilder MapKeys { get; set; } = null!;
    public MethodBuilder MapValues { get; set; } = null!;
    public MethodBuilder MapEntries { get; set; } = null!;
    public MethodBuilder MapForEach { get; set; } = null!;

    // Set support
    public MethodBuilder CreateSet { get; set; } = null!;
    public MethodBuilder CreateSetFromArray { get; set; } = null!;
    public MethodBuilder SetSize { get; set; } = null!;
    public MethodBuilder SetAdd { get; set; } = null!;
    public MethodBuilder SetHas { get; set; } = null!;
    public MethodBuilder SetDelete { get; set; } = null!;
    public MethodBuilder SetClear { get; set; } = null!;
    public MethodBuilder SetKeys { get; set; } = null!;
    public MethodBuilder SetValues { get; set; } = null!;
    public MethodBuilder SetEntries { get; set; } = null!;
    public MethodBuilder SetForEach { get; set; } = null!;

    // ES2025 Set Operations
    public MethodBuilder SetUnion { get; set; } = null!;
    public MethodBuilder SetIntersection { get; set; } = null!;
    public MethodBuilder SetDifference { get; set; } = null!;
    public MethodBuilder SetSymmetricDifference { get; set; } = null!;
    public MethodBuilder SetIsSubsetOf { get; set; } = null!;
    public MethodBuilder SetIsSupersetOf { get; set; } = null!;
    public MethodBuilder SetIsDisjointFrom { get; set; } = null!;

    // WeakMap support
    public MethodBuilder CreateWeakMap { get; set; } = null!;
    public MethodBuilder WeakMapGet { get; set; } = null!;
    public MethodBuilder WeakMapSet { get; set; } = null!;
    public MethodBuilder WeakMapHas { get; set; } = null!;
    public MethodBuilder WeakMapDelete { get; set; } = null!;

    // WeakSet support
    public MethodBuilder CreateWeakSet { get; set; } = null!;
    public MethodBuilder WeakSetAdd { get; set; } = null!;
    public MethodBuilder WeakSetHas { get; set; } = null!;
    public MethodBuilder WeakSetDelete { get; set; } = null!;

    // WeakMap/WeakSet validation helpers
    public MethodBuilder ValidateWeakMapKey { get; set; } = null!;
    public MethodBuilder ValidateWeakSetValue { get; set; } = null!;

    // The emitted TSDate class
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSDate
    public TypeBuilder TSDateType { get; set; } = null!;
    public ConstructorBuilder TSDateCtorNoArgs { get; set; } = null!;
    public ConstructorBuilder TSDateCtorMilliseconds { get; set; } = null!;
    public ConstructorBuilder TSDateCtorString { get; set; } = null!;
    public ConstructorBuilder TSDateCtorComponents { get; set; } = null!;
    public MethodBuilder TSDateNowStatic { get; set; } = null!;
    /// <summary>
    /// Dictionary of $TSDate instance methods by name. Used to lookup methods before CreateType().
    /// </summary>
    public Dictionary<string, MethodBuilder> TSDateMethods { get; } = new();

    // Date support
    public MethodBuilder DateNow { get; set; } = null!;
    public MethodBuilder CreateDateNoArgs { get; set; } = null!;
    public MethodBuilder CreateDateFromValue { get; set; } = null!;
    public MethodBuilder CreateDateFromComponents { get; set; } = null!;
    public MethodBuilder DateToString { get; set; } = null!;
    public MethodBuilder DateGetTime { get; set; } = null!;
    public MethodBuilder DateGetFullYear { get; set; } = null!;
    public MethodBuilder DateGetMonth { get; set; } = null!;
    public MethodBuilder DateGetDate { get; set; } = null!;
    public MethodBuilder DateGetDay { get; set; } = null!;
    public MethodBuilder DateGetHours { get; set; } = null!;
    public MethodBuilder DateGetMinutes { get; set; } = null!;
    public MethodBuilder DateGetSeconds { get; set; } = null!;
    public MethodBuilder DateGetMilliseconds { get; set; } = null!;
    public MethodBuilder DateGetTimezoneOffset { get; set; } = null!;
    public MethodBuilder DateSetTime { get; set; } = null!;
    public MethodBuilder DateSetFullYear { get; set; } = null!;
    public MethodBuilder DateSetMonth { get; set; } = null!;
    public MethodBuilder DateSetDate { get; set; } = null!;
    public MethodBuilder DateSetHours { get; set; } = null!;
    public MethodBuilder DateSetMinutes { get; set; } = null!;
    public MethodBuilder DateSetSeconds { get; set; } = null!;
    public MethodBuilder DateSetMilliseconds { get; set; } = null!;
    public MethodBuilder DateToISOString { get; set; } = null!;
    public MethodBuilder DateToDateString { get; set; } = null!;
    public MethodBuilder DateToTimeString { get; set; } = null!;
    public MethodBuilder DateValueOf { get; set; } = null!;

    // RegExp support
    public MethodBuilder CreateRegExp { get; set; } = null!;
    public MethodBuilder CreateRegExpWithFlags { get; set; } = null!;
    public MethodBuilder RegExpTest { get; set; } = null!;
    public MethodBuilder RegExpExec { get; set; } = null!;
    public MethodBuilder RegExpToString { get; set; } = null!;
    public MethodBuilder RegExpGetSource { get; set; } = null!;
    public MethodBuilder RegExpGetFlags { get; set; } = null!;
    public MethodBuilder RegExpGetGlobal { get; set; } = null!;
    public MethodBuilder RegExpGetIgnoreCase { get; set; } = null!;
    public MethodBuilder RegExpGetMultiline { get; set; } = null!;
    public MethodBuilder RegExpGetLastIndex { get; set; } = null!;
    public MethodBuilder RegExpSetLastIndex { get; set; } = null!;
    public MethodBuilder StringMatchRegExp { get; set; } = null!;
    public MethodBuilder StringReplaceRegExp { get; set; } = null!;
    public MethodBuilder StringSearchRegExp { get; set; } = null!;
    public MethodBuilder StringSplitRegExp { get; set; } = null!;

    // Dynamic import support
    public MethodBuilder DynamicImportModule { get; set; } = null!;
    public MethodBuilder WrapTaskAsPromise { get; set; } = null!;

    // Iterator protocol support
    public MethodBuilder GetIterator { get; set; } = null!;

    // Iterator wrapper type (implements IEnumerator<object?> for custom iterables)
    public TypeBuilder IteratorWrapperType { get; set; } = null!;
    public ConstructorBuilder IteratorWrapperCtor { get; set; } = null!;

    // Iterator protocol helper methods
    public MethodBuilder GetIteratorFunction { get; set; } = null!;  // Returns iterator function or null
    public MethodBuilder InvokeIteratorNext { get; set; } = null!;   // Calls next() on iterator
    public MethodBuilder GetIteratorDone { get; set; } = null!;      // Extracts done from result
    public MethodBuilder GetIteratorValue { get; set; } = null!;     // Extracts value from result
    public MethodBuilder IterateToList { get; set; } = null!;        // Converts any iterable to List<object>

    // Generator interface ($IGenerator extends IEnumerator<object> with Return/Throw)
    public TypeBuilder GeneratorInterfaceType { get; set; } = null!;
    public MethodBuilder GeneratorReturnMethod { get; set; } = null!;
    public MethodBuilder GeneratorThrowMethod { get; set; } = null!;
    public MethodBuilder GeneratorNextMethod { get; set; } = null!;

    // Async Generator interface ($IAsyncGenerator extends IAsyncEnumerator<object> with async Return/Throw)
    public TypeBuilder AsyncGeneratorInterfaceType { get; set; } = null!;
    public MethodBuilder AsyncGeneratorNextMethod { get; set; } = null!;
    public MethodBuilder AsyncGeneratorReturnMethod { get; set; } = null!;
    public MethodBuilder AsyncGeneratorThrowMethod { get; set; } = null!;

    // Async Generator await continuation helper
    public MethodBuilder AsyncGeneratorAwaitContinue { get; set; } = null!;
}
