using System.Reflection;
using System.Reflection.Emit;

namespace SharpTS.Compilation;

/// <summary>
/// Holds references to runtime support types and methods emitted into compiled assemblies.
/// </summary>
/// <remarks>
/// Enables standalone DLLs without requiring SharpTS.dll at runtime. Contains references
/// to emitted types (TSFunction, TSRuntime) and helper methods (console.log, type coercion,
/// array/object operations, invocation helpers). These are generated by <see cref="RuntimeTypes"/>
/// and used by <see cref="ILEmitter"/> when emitting calls to runtime support code.
/// </remarks>
/// <seealso cref="RuntimeTypes"/>
/// <seealso cref="ILCompiler"/>
/// <seealso cref="ILEmitter"/>
public class EmittedRuntime
{
    // The emitted $Undefined singleton class
    public Type UndefinedType { get; set; } = null!;
    public FieldInfo UndefinedInstance { get; set; } = null!;

    // The emitted TSFunction class
    public TypeBuilder TSFunctionType { get; set; } = null!;
    public ConstructorBuilder TSFunctionCtor { get; set; } = null!;
    public MethodBuilder TSFunctionInvoke { get; set; } = null!;
    public MethodBuilder TSFunctionInvokeWithThis { get; set; } = null!;
    public MethodBuilder TSFunctionBindThis { get; set; } = null!;

    // The emitted TSNamespace class
    public TypeBuilder TSNamespaceType { get; set; } = null!;
    public ConstructorBuilder TSNamespaceCtor { get; set; } = null!;
    public MethodBuilder TSNamespaceGet { get; set; } = null!;
    public MethodBuilder TSNamespaceSet { get; set; } = null!;

    // The emitted ReferenceEqualityComparer class (for Map/Set key equality)
    public TypeBuilder ReferenceEqualityComparerType { get; set; } = null!;
    public FieldBuilder ReferenceEqualityComparerInstance { get; set; } = null!;

    // The emitted runtime helper class
    public TypeBuilder RuntimeType { get; set; } = null!;

    // Console methods
    public MethodBuilder ConsoleLog { get; set; } = null!;
    public MethodBuilder ConsoleLogMultiple { get; set; } = null!;
    public MethodBuilder ConsoleError { get; set; } = null!;
    public MethodBuilder ConsoleErrorMultiple { get; set; } = null!;
    public MethodBuilder ConsoleWarn { get; set; } = null!;
    public MethodBuilder ConsoleWarnMultiple { get; set; } = null!;
    public MethodBuilder ConsoleClear { get; set; } = null!;
    public MethodBuilder ConsoleTime { get; set; } = null!;
    public MethodBuilder ConsoleTimeEnd { get; set; } = null!;
    public MethodBuilder ConsoleTimeLog { get; set; } = null!;
    public FieldBuilder ConsoleTimersField { get; set; } = null!;

    // Union type marker interface (for fast union type detection)
    public Type IUnionTypeInterface { get; set; } = null!;
    public MethodInfo IUnionTypeValueGetter { get; set; } = null!;

    // Type coercion methods
    public MethodBuilder Stringify { get; set; } = null!;
    public MethodBuilder ToNumber { get; set; } = null!;
    public MethodBuilder IsTruthy { get; set; } = null!;
    public MethodBuilder TypeOf { get; set; } = null!;
    public MethodBuilder InstanceOf { get; set; } = null!;

    // Operator methods
    public MethodBuilder Add { get; set; } = null!;
    public new MethodBuilder Equals { get; set; } = null!;

    // Array methods
    public MethodBuilder CreateArray { get; set; } = null!;
    public MethodBuilder GetLength { get; set; } = null!;
    public MethodBuilder GetElement { get; set; } = null!;
    public MethodBuilder GetKeys { get; set; } = null!;
    public MethodBuilder GetValues { get; set; } = null!;
    public MethodBuilder GetEntries { get; set; } = null!;
    public MethodBuilder IsArray { get; set; } = null!;
    public MethodBuilder ArrayFrom { get; set; } = null!;
    public MethodBuilder ArrayOf { get; set; } = null!;
    public MethodBuilder SpreadArray { get; set; } = null!;
    public MethodBuilder ConcatArrays { get; set; } = null!;
    public MethodBuilder ExpandCallArgs { get; set; } = null!;
    public MethodBuilder ArrayPop { get; set; } = null!;
    public MethodBuilder ArrayShift { get; set; } = null!;
    public MethodBuilder ArrayUnshift { get; set; } = null!;
    public MethodBuilder ArraySlice { get; set; } = null!;
    public MethodBuilder ArrayMap { get; set; } = null!;
    public MethodBuilder ArrayFilter { get; set; } = null!;
    public MethodBuilder ArrayForEach { get; set; } = null!;
    public MethodBuilder ArrayPush { get; set; } = null!;
    public MethodBuilder ArrayFind { get; set; } = null!;
    public MethodBuilder ArrayFindIndex { get; set; } = null!;
    public MethodBuilder ArraySome { get; set; } = null!;
    public MethodBuilder ArrayEvery { get; set; } = null!;
    public MethodBuilder ArrayReduce { get; set; } = null!;
    public MethodBuilder ArrayIncludes { get; set; } = null!;
    public MethodBuilder ArrayIndexOf { get; set; } = null!;
    public MethodBuilder ArrayJoin { get; set; } = null!;
    public MethodBuilder ArrayConcat { get; set; } = null!;
    public MethodBuilder ArrayReverse { get; set; } = null!;
    public MethodBuilder ArrayFlat { get; set; } = null!;
    public MethodBuilder ArrayFlatMap { get; set; } = null!;
    public MethodBuilder ArrayFlatHelper { get; set; } = null!;
    public MethodBuilder ArraySort { get; set; } = null!;
    public MethodBuilder ArrayToSorted { get; set; } = null!;
    public MethodBuilder ArraySplice { get; set; } = null!;
    public MethodBuilder ArrayToSpliced { get; set; } = null!;
    public MethodBuilder ToIntegerOrInfinity { get; set; } = null!;
    public MethodBuilder ArrayFindLast { get; set; } = null!;
    public MethodBuilder ArrayFindLastIndex { get; set; } = null!;
    public MethodBuilder ArrayToReversed { get; set; } = null!;
    public MethodBuilder ArrayWith { get; set; } = null!;

    // String methods
    public MethodBuilder StringCharAt { get; set; } = null!;
    public MethodBuilder StringSubstring { get; set; } = null!;
    public MethodBuilder StringIndexOf { get; set; } = null!;
    public MethodBuilder StringToUpperCase { get; set; } = null!;
    public MethodBuilder StringToLowerCase { get; set; } = null!;
    public MethodBuilder StringTrim { get; set; } = null!;
    public MethodBuilder StringReplace { get; set; } = null!;
    public MethodBuilder StringSplit { get; set; } = null!;
    public MethodBuilder StringIncludes { get; set; } = null!;
    public MethodBuilder StringStartsWith { get; set; } = null!;
    public MethodBuilder StringEndsWith { get; set; } = null!;
    public MethodBuilder StringSlice { get; set; } = null!;
    public MethodBuilder StringRepeat { get; set; } = null!;
    public MethodBuilder StringPadStart { get; set; } = null!;
    public MethodBuilder StringPadEnd { get; set; } = null!;
    public MethodBuilder StringCharCodeAt { get; set; } = null!;
    public MethodBuilder StringConcat { get; set; } = null!;
    public MethodBuilder StringLastIndexOf { get; set; } = null!;
    public MethodBuilder StringTrimStart { get; set; } = null!;
    public MethodBuilder StringTrimEnd { get; set; } = null!;
    public MethodBuilder StringReplaceAll { get; set; } = null!;
    public MethodBuilder StringAt { get; set; } = null!;

    // Object methods
    public MethodBuilder CreateObject { get; set; } = null!;
    public MethodBuilder GetProperty { get; set; } = null!;
    public MethodBuilder SetProperty { get; set; } = null!;
    public MethodBuilder SetPropertyStrict { get; set; } = null!;
    public MethodBuilder DeleteProperty { get; set; } = null!;
    public MethodBuilder GetFieldsProperty { get; set; } = null!;
    public MethodBuilder SetFieldsProperty { get; set; } = null!;
    public MethodBuilder SetFieldsPropertyStrict { get; set; } = null!;
    public MethodBuilder GetArrayMethod { get; set; } = null!;
    public MethodBuilder GetListProperty { get; set; } = null!;
    public MethodBuilder MergeIntoObject { get; set; } = null!;
    public MethodBuilder MergeIntoTSObject { get; set; } = null!;
    public MethodBuilder ToPascalCase { get; set; } = null!;
    public MethodBuilder GetIndex { get; set; } = null!;
    public MethodBuilder SetIndex { get; set; } = null!;
    public MethodBuilder SetIndexStrict { get; set; } = null!;
    public MethodBuilder ObjectFromEntries { get; set; } = null!;
    public MethodBuilder ObjectHasOwn { get; set; } = null!;
    public MethodBuilder ObjectAssign { get; set; } = null!;
    public MethodBuilder ObjectFreeze { get; set; } = null!;
    public MethodBuilder ObjectSeal { get; set; } = null!;
    public MethodBuilder ObjectIsFrozen { get; set; } = null!;
    public MethodBuilder ObjectIsSealed { get; set; } = null!;
    public FieldBuilder FrozenObjectsField { get; set; } = null!;
    public FieldBuilder SealedObjectsField { get; set; } = null!;

    // Invocation methods
    public MethodBuilder InvokeValue { get; set; } = null!;
    public MethodBuilder InvokeMethodValue { get; set; } = null!;
    public MethodBuilder GetSuperMethod { get; set; } = null!;

    // Function methods (bind/call/apply)
    public TypeBuilder BoundTSFunctionType { get; set; } = null!;
    public ConstructorBuilder BoundTSFunctionCtor { get; set; } = null!;
    public MethodBuilder BoundTSFunctionInvoke { get; set; } = null!;
    public MethodBuilder BoundTSFunctionInvokeWithThis { get; set; } = null!;
    public TypeBuilder FunctionBindWrapperType { get; set; } = null!;
    public ConstructorBuilder FunctionBindWrapperCtor { get; set; } = null!;
    public TypeBuilder FunctionCallWrapperType { get; set; } = null!;
    public ConstructorBuilder FunctionCallWrapperCtor { get; set; } = null!;
    public TypeBuilder FunctionApplyWrapperType { get; set; } = null!;
    public ConstructorBuilder FunctionApplyWrapperCtor { get; set; } = null!;
    public MethodBuilder GetFunctionMethod { get; set; } = null!;

    // Exception methods
    public MethodBuilder CreateException { get; set; } = null!;
    public MethodBuilder WrapException { get; set; } = null!;

    // Utility methods
    public MethodBuilder Random { get; set; } = null!;
    public MethodBuilder GetEnumMemberName { get; set; } = null!;
    public MethodBuilder ConcatTemplate { get; set; } = null!;
    public MethodBuilder InvokeTaggedTemplate { get; set; } = null!;
    public MethodBuilder ObjectRest { get; set; } = null!;

    // JSON methods
    public MethodBuilder JsonParse { get; set; } = null!;
    public MethodBuilder JsonParseWithReviver { get; set; } = null!;
    public MethodBuilder JsonStringify { get; set; } = null!;
    public MethodBuilder JsonStringifyFull { get; set; } = null!;

    // Symbol support
    public TypeBuilder TSSymbolType { get; set; } = null!;
    public ConstructorBuilder TSSymbolCtor { get; set; } = null!;
    public MethodBuilder CreateSymbol { get; set; } = null!;

    // Well-known symbols (static fields on $TSSymbol)
    public FieldBuilder SymbolIterator { get; set; } = null!;
    public FieldBuilder SymbolAsyncIterator { get; set; } = null!;
    public FieldBuilder SymbolToStringTag { get; set; } = null!;
    public FieldBuilder SymbolHasInstance { get; set; } = null!;
    public FieldBuilder SymbolIsConcatSpreadable { get; set; } = null!;
    public FieldBuilder SymbolToPrimitive { get; set; } = null!;
    public FieldBuilder SymbolSpecies { get; set; } = null!;
    public FieldBuilder SymbolUnscopables { get; set; } = null!;

    // Symbol storage for compiled objects (symbol as object key)
    public FieldBuilder SymbolStorageField { get; set; } = null!;
    public MethodBuilder GetSymbolDictMethod { get; set; } = null!;
    public MethodBuilder IsSymbolMethod { get; set; } = null!;

    // BigInt support
    public MethodBuilder CreateBigInt { get; set; } = null!;
    public MethodBuilder BigIntAdd { get; set; } = null!;
    public MethodBuilder BigIntSubtract { get; set; } = null!;
    public MethodBuilder BigIntMultiply { get; set; } = null!;
    public MethodBuilder BigIntDivide { get; set; } = null!;
    public MethodBuilder BigIntRemainder { get; set; } = null!;
    public MethodBuilder BigIntPow { get; set; } = null!;
    public MethodBuilder BigIntNegate { get; set; } = null!;
    public MethodBuilder BigIntBitwiseAnd { get; set; } = null!;
    public MethodBuilder BigIntBitwiseOr { get; set; } = null!;
    public MethodBuilder BigIntBitwiseXor { get; set; } = null!;
    public MethodBuilder BigIntBitwiseNot { get; set; } = null!;
    public MethodBuilder BigIntLeftShift { get; set; } = null!;
    public MethodBuilder BigIntRightShift { get; set; } = null!;
    public MethodBuilder BigIntEquals { get; set; } = null!;
    public MethodBuilder BigIntLessThan { get; set; } = null!;
    public MethodBuilder BigIntLessThanOrEqual { get; set; } = null!;
    public MethodBuilder BigIntGreaterThan { get; set; } = null!;
    public MethodBuilder BigIntGreaterThanOrEqual { get; set; } = null!;

    // Promise support
    public MethodBuilder PromiseResolve { get; set; } = null!;
    public MethodBuilder PromiseReject { get; set; } = null!;
    public MethodBuilder PromiseAll { get; set; } = null!;
    public MethodBuilder PromiseRace { get; set; } = null!;
    public MethodBuilder PromiseThen { get; set; } = null!;
    public MethodBuilder PromiseCatch { get; set; } = null!;
    public MethodBuilder PromiseFinally { get; set; } = null!;
    public MethodBuilder PromiseAllSettled { get; set; } = null!;
    public MethodBuilder PromiseAny { get; set; } = null!;

    // Promise callback helpers (direct $TSFunction.Invoke without reflection)
    public MethodBuilder InvokeCallback { get; set; } = null!;
    public MethodBuilder InvokeCallbackNoArgs { get; set; } = null!;

    // PromiseAllSettled helper
    public MethodBuilder ProcessElementSettled { get; set; } = null!;

    // Timer support ($TSTimeout type and global functions)
    public TypeBuilder TSTimeoutType { get; set; } = null!;
    public ConstructorBuilder TSTimeoutCtor { get; set; } = null!;
    public MethodBuilder TSTimeoutCancel { get; set; } = null!;
    public MethodBuilder TSTimeoutRef { get; set; } = null!;
    public MethodBuilder TSTimeoutUnref { get; set; } = null!;
    public MethodBuilder TSTimeoutHasRefGetter { get; set; } = null!;
    public MethodBuilder SetTimeout { get; set; } = null!;
    public MethodBuilder ClearTimeout { get; set; } = null!;

    // Timer closure for callback execution
    public TypeBuilder TimeoutClosureType { get; set; } = null!;
    public ConstructorBuilder TimeoutClosureCtor { get; set; } = null!;
    public FieldBuilder TimeoutClosureCallback { get; set; } = null!;
    public FieldBuilder TimeoutClosureArgs { get; set; } = null!;
    public FieldBuilder TimeoutClosureCts { get; set; } = null!;
    public MethodBuilder TimeoutClosureExecute { get; set; } = null!;

    // Interval closure for callback execution (includes delay for rescheduling)
    public TypeBuilder IntervalClosureType { get; set; } = null!;
    public ConstructorBuilder IntervalClosureCtor { get; set; } = null!;
    public FieldBuilder IntervalClosureCallback { get; set; } = null!;
    public FieldBuilder IntervalClosureArgs { get; set; } = null!;
    public FieldBuilder IntervalClosureCts { get; set; } = null!;
    public FieldBuilder IntervalClosureDelayMs { get; set; } = null!;
    public MethodBuilder IntervalClosureExecuteIteration { get; set; } = null!;

    // Interval methods
    public MethodBuilder SetInterval { get; set; } = null!;
    public MethodBuilder ClearInterval { get; set; } = null!;

    // Number methods
    public MethodBuilder NumberParseInt { get; set; } = null!;
    public MethodBuilder NumberParseFloat { get; set; } = null!;
    public MethodBuilder NumberIsNaN { get; set; } = null!;
    public MethodBuilder NumberIsFinite { get; set; } = null!;
    public MethodBuilder NumberIsInteger { get; set; } = null!;
    public MethodBuilder NumberIsSafeInteger { get; set; } = null!;
    public MethodBuilder GlobalIsNaN { get; set; } = null!;
    public MethodBuilder GlobalIsFinite { get; set; } = null!;
    public MethodBuilder NumberToFixed { get; set; } = null!;
    public MethodBuilder NumberToPrecision { get; set; } = null!;
    public MethodBuilder NumberToExponential { get; set; } = null!;
    public MethodBuilder NumberToStringRadix { get; set; } = null!;

    // Number helper methods (for standalone execution)
    public MethodBuilder ParseIntHelper { get; set; } = null!;
    public MethodBuilder GetDigitValue { get; set; } = null!;
    public MethodBuilder ConvertIntToRadix { get; set; } = null!;
    public MethodBuilder GetValidFloatPart { get; set; } = null!;

    // Map support
    public MethodBuilder CreateMap { get; set; } = null!;
    public MethodBuilder CreateMapFromEntries { get; set; } = null!;
    public MethodBuilder MapSize { get; set; } = null!;
    public MethodBuilder MapGet { get; set; } = null!;
    public MethodBuilder MapSet { get; set; } = null!;
    public MethodBuilder MapHas { get; set; } = null!;
    public MethodBuilder MapDelete { get; set; } = null!;
    public MethodBuilder MapClear { get; set; } = null!;
    public MethodBuilder MapKeys { get; set; } = null!;
    public MethodBuilder MapValues { get; set; } = null!;
    public MethodBuilder MapEntries { get; set; } = null!;
    public MethodBuilder MapForEach { get; set; } = null!;

    // Set support
    public MethodBuilder CreateSet { get; set; } = null!;
    public MethodBuilder CreateSetFromArray { get; set; } = null!;
    public MethodBuilder SetSize { get; set; } = null!;
    public MethodBuilder SetAdd { get; set; } = null!;
    public MethodBuilder SetHas { get; set; } = null!;
    public MethodBuilder SetDelete { get; set; } = null!;
    public MethodBuilder SetClear { get; set; } = null!;
    public MethodBuilder SetKeys { get; set; } = null!;
    public MethodBuilder SetValues { get; set; } = null!;
    public MethodBuilder SetEntries { get; set; } = null!;
    public MethodBuilder SetForEach { get; set; } = null!;

    // ES2025 Set Operations
    public MethodBuilder SetUnion { get; set; } = null!;
    public MethodBuilder SetIntersection { get; set; } = null!;
    public MethodBuilder SetDifference { get; set; } = null!;
    public MethodBuilder SetSymmetricDifference { get; set; } = null!;
    public MethodBuilder SetIsSubsetOf { get; set; } = null!;
    public MethodBuilder SetIsSupersetOf { get; set; } = null!;
    public MethodBuilder SetIsDisjointFrom { get; set; } = null!;

    // WeakMap support
    public MethodBuilder CreateWeakMap { get; set; } = null!;
    public MethodBuilder WeakMapGet { get; set; } = null!;
    public MethodBuilder WeakMapSet { get; set; } = null!;
    public MethodBuilder WeakMapHas { get; set; } = null!;
    public MethodBuilder WeakMapDelete { get; set; } = null!;

    // WeakSet support
    public MethodBuilder CreateWeakSet { get; set; } = null!;
    public MethodBuilder WeakSetAdd { get; set; } = null!;
    public MethodBuilder WeakSetHas { get; set; } = null!;
    public MethodBuilder WeakSetDelete { get; set; } = null!;

    // WeakMap/WeakSet validation helpers
    public MethodBuilder ValidateWeakMapKey { get; set; } = null!;
    public MethodBuilder ValidateWeakSetValue { get; set; } = null!;

    // The emitted TSDate class
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSDate
    public TypeBuilder TSDateType { get; set; } = null!;
    public ConstructorBuilder TSDateCtorNoArgs { get; set; } = null!;
    public ConstructorBuilder TSDateCtorMilliseconds { get; set; } = null!;
    public ConstructorBuilder TSDateCtorString { get; set; } = null!;
    public ConstructorBuilder TSDateCtorComponents { get; set; } = null!;
    public MethodBuilder TSDateNowStatic { get; set; } = null!;
    /// <summary>
    /// Dictionary of $TSDate instance methods by name. Used to lookup methods before CreateType().
    /// </summary>
    public Dictionary<string, MethodBuilder> TSDateMethods { get; } = new();

    // Date support
    public MethodBuilder DateNow { get; set; } = null!;
    public MethodBuilder CreateDateNoArgs { get; set; } = null!;
    public MethodBuilder CreateDateFromValue { get; set; } = null!;
    public MethodBuilder CreateDateFromComponents { get; set; } = null!;
    public MethodBuilder DateToString { get; set; } = null!;
    public MethodBuilder DateGetTime { get; set; } = null!;
    public MethodBuilder DateGetFullYear { get; set; } = null!;
    public MethodBuilder DateGetMonth { get; set; } = null!;
    public MethodBuilder DateGetDate { get; set; } = null!;
    public MethodBuilder DateGetDay { get; set; } = null!;
    public MethodBuilder DateGetHours { get; set; } = null!;
    public MethodBuilder DateGetMinutes { get; set; } = null!;
    public MethodBuilder DateGetSeconds { get; set; } = null!;
    public MethodBuilder DateGetMilliseconds { get; set; } = null!;
    public MethodBuilder DateGetTimezoneOffset { get; set; } = null!;
    public MethodBuilder DateSetTime { get; set; } = null!;
    public MethodBuilder DateSetFullYear { get; set; } = null!;
    public MethodBuilder DateSetMonth { get; set; } = null!;
    public MethodBuilder DateSetDate { get; set; } = null!;
    public MethodBuilder DateSetHours { get; set; } = null!;
    public MethodBuilder DateSetMinutes { get; set; } = null!;
    public MethodBuilder DateSetSeconds { get; set; } = null!;
    public MethodBuilder DateSetMilliseconds { get; set; } = null!;
    public MethodBuilder DateToISOString { get; set; } = null!;
    public MethodBuilder DateToDateString { get; set; } = null!;
    public MethodBuilder DateToTimeString { get; set; } = null!;
    public MethodBuilder DateValueOf { get; set; } = null!;

    // RegExp support - $Runtime wrapper methods
    public MethodBuilder CreateRegExp { get; set; } = null!;
    public MethodBuilder CreateRegExpWithFlags { get; set; } = null!;
    public MethodBuilder RegExpTest { get; set; } = null!;
    public MethodBuilder RegExpExec { get; set; } = null!;
    public MethodBuilder RegExpToString { get; set; } = null!;
    public MethodBuilder RegExpGetSource { get; set; } = null!;
    public MethodBuilder RegExpGetFlags { get; set; } = null!;
    public MethodBuilder RegExpGetGlobal { get; set; } = null!;
    public MethodBuilder RegExpGetIgnoreCase { get; set; } = null!;
    public MethodBuilder RegExpGetMultiline { get; set; } = null!;
    public MethodBuilder RegExpGetLastIndex { get; set; } = null!;
    public MethodBuilder RegExpSetLastIndex { get; set; } = null!;
    public MethodBuilder StringMatchRegExp { get; set; } = null!;
    public MethodBuilder StringReplaceRegExp { get; set; } = null!;
    public MethodBuilder StringSearchRegExp { get; set; } = null!;
    public MethodBuilder StringSplitRegExp { get; set; } = null!;

    // RegExp support - emitted $RegExp type for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSRegExp
    public TypeBuilder TSRegExpType { get; set; } = null!;
    public ConstructorBuilder TSRegExpCtorPattern { get; set; } = null!;
    public ConstructorBuilder TSRegExpCtorPatternFlags { get; set; } = null!;
    public MethodBuilder TSRegExpNormalizeFlags { get; set; } = null!;
    public MethodBuilder TSRegExpSourceGetter { get; set; } = null!;
    public MethodBuilder TSRegExpFlagsGetter { get; set; } = null!;
    public MethodBuilder TSRegExpGlobalGetter { get; set; } = null!;
    public MethodBuilder TSRegExpIgnoreCaseGetter { get; set; } = null!;
    public MethodBuilder TSRegExpMultilineGetter { get; set; } = null!;
    public MethodBuilder TSRegExpLastIndexGetter { get; set; } = null!;
    public MethodBuilder TSRegExpLastIndexSetter { get; set; } = null!;
    public MethodBuilder TSRegExpTestMethod { get; set; } = null!;
    public MethodBuilder TSRegExpExecMethod { get; set; } = null!;
    public MethodBuilder TSRegExpToStringMethod { get; set; } = null!;

    // Error support - emitted types for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSError and subclasses

    // $Error base class
    public Type TSErrorType { get; set; } = null!;
    public ConstructorBuilder TSErrorCtorMessage { get; set; } = null!;
    public ConstructorBuilder TSErrorCtorNameMessage { get; set; } = null!;
    public MethodBuilder TSErrorNameGetter { get; set; } = null!;
    public MethodBuilder TSErrorNameSetter { get; set; } = null!;
    public MethodBuilder TSErrorMessageGetter { get; set; } = null!;
    public MethodBuilder TSErrorMessageSetter { get; set; } = null!;
    public MethodBuilder TSErrorStackGetter { get; set; } = null!;
    public MethodBuilder TSErrorStackSetter { get; set; } = null!;
    public MethodBuilder TSErrorToStringMethod { get; set; } = null!;
    public MethodBuilder TSErrorCaptureStackTrace { get; set; } = null!;

    // $TypeError
    public Type TSTypeErrorType { get; set; } = null!;
    public ConstructorBuilder TSTypeErrorCtor { get; set; } = null!;

    // $RangeError
    public Type TSRangeErrorType { get; set; } = null!;
    public ConstructorBuilder TSRangeErrorCtor { get; set; } = null!;

    // $ReferenceError
    public Type TSReferenceErrorType { get; set; } = null!;
    public ConstructorBuilder TSReferenceErrorCtor { get; set; } = null!;

    // $SyntaxError
    public Type TSSyntaxErrorType { get; set; } = null!;
    public ConstructorBuilder TSSyntaxErrorCtor { get; set; } = null!;

    // $URIError
    public Type TSURIErrorType { get; set; } = null!;
    public ConstructorBuilder TSURIErrorCtor { get; set; } = null!;

    // $EvalError
    public Type TSEvalErrorType { get; set; } = null!;
    public ConstructorBuilder TSEvalErrorCtor { get; set; } = null!;

    // $AggregateError
    public Type TSAggregateErrorType { get; set; } = null!;
    public ConstructorBuilder TSAggregateErrorCtor { get; set; } = null!;
    public MethodBuilder TSAggregateErrorErrorsGetter { get; set; } = null!;

    // Error helper methods in $Runtime
    public MethodBuilder CreateError { get; set; } = null!;
    public MethodBuilder ErrorGetName { get; set; } = null!;
    public MethodBuilder ErrorGetMessage { get; set; } = null!;
    public MethodBuilder ErrorGetStack { get; set; } = null!;
    public MethodBuilder ErrorSetName { get; set; } = null!;
    public MethodBuilder ErrorSetMessage { get; set; } = null!;
    public MethodBuilder ErrorSetStack { get; set; } = null!;
    public MethodBuilder ErrorToString { get; set; } = null!;
    public MethodBuilder AggregateErrorGetErrors { get; set; } = null!;

    // Promise type - emitted for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSPromise
    public Type TSPromiseType { get; set; } = null!;
    public ConstructorBuilder TSPromiseCtor { get; set; } = null!;
    public MethodBuilder TSPromiseTaskGetter { get; set; } = null!;
    public MethodBuilder TSPromiseResolve { get; set; } = null!;
    public MethodBuilder TSPromiseReject { get; set; } = null!;
    public MethodBuilder TSPromiseGetValueAsync { get; set; } = null!;

    // Promise rejected exception
    public Type TSPromiseRejectedExceptionType { get; set; } = null!;
    public ConstructorBuilder TSPromiseRejectedExceptionCtor { get; set; } = null!;
    public MethodBuilder TSPromiseRejectedExceptionReasonGetter { get; set; } = null!;

    // Dynamic import support
    public MethodBuilder DynamicImportModule { get; set; } = null!;
    public MethodBuilder WrapTaskAsPromise { get; set; } = null!;

    // $Array type - emitted for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSArray
    public Type TSArrayType { get; set; } = null!;
    public ConstructorBuilder TSArrayCtor { get; set; } = null!;
    public MethodBuilder TSArrayElementsGetter { get; set; } = null!;
    public MethodBuilder TSArrayIsFrozenGetter { get; set; } = null!;
    public MethodBuilder TSArrayIsSealedGetter { get; set; } = null!;
    public MethodBuilder TSArrayFreeze { get; set; } = null!;
    public MethodBuilder TSArraySeal { get; set; } = null!;
    public MethodBuilder TSArrayGet { get; set; } = null!;
    public MethodBuilder TSArraySet { get; set; } = null!;
    public MethodBuilder TSArraySetStrict { get; set; } = null!;
    public MethodBuilder TSArrayToString { get; set; } = null!;

    // $Object type - emitted for standalone assemblies
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSObject
    public Type TSObjectType { get; set; } = null!;
    public ConstructorBuilder TSObjectCtor { get; set; } = null!;
    public MethodBuilder TSObjectFieldsGetter { get; set; } = null!;
    public MethodBuilder TSObjectIsFrozenGetter { get; set; } = null!;
    public MethodBuilder TSObjectIsSealedGetter { get; set; } = null!;
    public MethodBuilder TSObjectFreeze { get; set; } = null!;
    public MethodBuilder TSObjectSeal { get; set; } = null!;
    public MethodBuilder TSObjectGetProperty { get; set; } = null!;
    public MethodBuilder TSObjectSetProperty { get; set; } = null!;
    public MethodBuilder TSObjectSetPropertyStrict { get; set; } = null!;
    public MethodBuilder TSObjectHasProperty { get; set; } = null!;
    public MethodBuilder TSObjectDeleteProperty { get; set; } = null!;
    public MethodBuilder TSObjectGetKeys { get; set; } = null!;
    public MethodBuilder TSObjectToString { get; set; } = null!;
    public MethodBuilder TSObjectDefineGetter { get; set; } = null!;
    public MethodBuilder TSObjectDefineSetter { get; set; } = null!;
    public MethodBuilder TSObjectHasGetter { get; set; } = null!;
    public MethodBuilder TSObjectHasSetter { get; set; } = null!;
    public MethodBuilder TSObjectGetGetter { get; set; } = null!;
    public MethodBuilder TSObjectGetSetter { get; set; } = null!;

    // Module registry for dynamic imports
    // Stores mapping from module path -> factory function that returns module namespace
    public FieldBuilder ModuleRegistry { get; set; } = null!;
    public MethodBuilder RegisterModule { get; set; } = null!;
    public MethodBuilder InitializeModuleRegistry { get; set; } = null!;

    // Iterator protocol support
    public MethodBuilder GetIterator { get; set; } = null!;

    // Iterator wrapper type (implements IEnumerator<object?> for custom iterables)
    public TypeBuilder IteratorWrapperType { get; set; } = null!;
    public ConstructorBuilder IteratorWrapperCtor { get; set; } = null!;

    // Iterator protocol helper methods
    public MethodBuilder GetIteratorFunction { get; set; } = null!;  // Returns iterator function or null
    public MethodBuilder InvokeIteratorNext { get; set; } = null!;   // Calls next() on iterator
    public MethodBuilder GetIteratorDone { get; set; } = null!;      // Extracts done from result
    public MethodBuilder GetIteratorValue { get; set; } = null!;     // Extracts value from result
    public MethodBuilder IterateToList { get; set; } = null!;        // Converts any iterable to List<object>

    // Generator interface ($IGenerator extends IEnumerator<object> with Return/Throw)
    public TypeBuilder GeneratorInterfaceType { get; set; } = null!;
    public MethodBuilder GeneratorReturnMethod { get; set; } = null!;
    public MethodBuilder GeneratorThrowMethod { get; set; } = null!;
    public MethodBuilder GeneratorNextMethod { get; set; } = null!;

    // Async Generator interface ($IAsyncGenerator extends IAsyncEnumerator<object> with async Return/Throw)
    public TypeBuilder AsyncGeneratorInterfaceType { get; set; } = null!;
    public MethodBuilder AsyncGeneratorNextMethod { get; set; } = null!;
    public MethodBuilder AsyncGeneratorReturnMethod { get; set; } = null!;
    public MethodBuilder AsyncGeneratorThrowMethod { get; set; } = null!;

    // Async Generator await continuation helper
    public MethodBuilder AsyncGeneratorAwaitContinue { get; set; } = null!;

    // OS module methods
    public MethodBuilder OsFreemem { get; set; } = null!;

    // Path module methods
    public MethodBuilder PathFormat { get; set; } = null!;

    // Fs module methods
    public MethodBuilder FsExistsSync { get; set; } = null!;
    public MethodBuilder FsReadFileSync { get; set; } = null!;
    public MethodBuilder FsWriteFileSync { get; set; } = null!;
    public MethodBuilder FsAppendFileSync { get; set; } = null!;
    public MethodBuilder FsUnlinkSync { get; set; } = null!;
    public MethodBuilder FsMkdirSync { get; set; } = null!;
    public MethodBuilder FsRmdirSync { get; set; } = null!;
    public MethodBuilder FsReaddirSync { get; set; } = null!;
    public MethodBuilder FsStatSync { get; set; } = null!;
    public MethodBuilder FsLstatSync { get; set; } = null!;
    public MethodBuilder FsRenameSync { get; set; } = null!;
    public MethodBuilder FsCopyFileSync { get; set; } = null!;
    public MethodBuilder FsAccessSync { get; set; } = null!;
    public MethodBuilder FsChmodSync { get; set; } = null!;
    public MethodBuilder FsChownSync { get; set; } = null!;
    public MethodBuilder FsLchownSync { get; set; } = null!;
    public MethodBuilder FsTruncateSync { get; set; } = null!;
    public MethodBuilder FsSymlinkSync { get; set; } = null!;
    public MethodBuilder FsReadlinkSync { get; set; } = null!;
    public MethodBuilder FsRealpathSync { get; set; } = null!;
    public MethodBuilder FsUtimesSync { get; set; } = null!;
    public MethodBuilder FsGetConstants { get; set; } = null!;
    public MethodBuilder FsCreateDirent { get; set; } = null!;

    // NodeError conversion helpers
    public MethodBuilder ConvertToNodeError { get; set; } = null!;
    public MethodBuilder ThrowNodeError { get; set; } = null!;

    // Process module methods
    public MethodBuilder ProcessGetEnv { get; set; } = null!;
    public MethodBuilder ProcessGetArgv { get; set; } = null!;
    public MethodBuilder ProcessHrtime { get; set; } = null!;
    public MethodBuilder ProcessUptime { get; set; } = null!;
    public MethodBuilder ProcessMemoryUsage { get; set; } = null!;

    // Process stdin/stdout/stderr stream methods
    public MethodBuilder StdinRead { get; set; } = null!;
    public MethodBuilder StdinIsTTY { get; set; } = null!;
    public MethodBuilder StdoutWrite { get; set; } = null!;
    public MethodBuilder StdoutIsTTY { get; set; } = null!;
    public MethodBuilder StderrWrite { get; set; } = null!;
    public MethodBuilder StderrIsTTY { get; set; } = null!;

    // globalThis methods (ES2020)
    public MethodBuilder GlobalThisGetProperty { get; set; } = null!;
    public MethodBuilder GlobalThisSetProperty { get; set; } = null!;

    // Crypto module methods
    public MethodBuilder CryptoCreateHash { get; set; } = null!;
    public MethodBuilder CryptoRandomBytes { get; set; } = null!;

    // $Hash type - emitted for standalone crypto support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSHash
    public Type TSHashType { get; set; } = null!;
    public ConstructorBuilder TSHashCtor { get; set; } = null!;
    public MethodBuilder TSHashUpdateMethod { get; set; } = null!;
    public MethodBuilder TSHashDigestMethod { get; set; } = null!;

    // $Hmac type - emitted for standalone crypto support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSHmac
    public MethodBuilder CryptoCreateHmac { get; set; } = null!;
    public Type TSHmacType { get; set; } = null!;
    public ConstructorBuilder TSHmacCtor { get; set; } = null!;
    public MethodBuilder TSHmacUpdateMethod { get; set; } = null!;
    public MethodBuilder TSHmacDigestMethod { get; set; } = null!;

    // $Cipher type - emitted for standalone crypto support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSCipher
    public MethodBuilder CryptoCreateCipheriv { get; set; } = null!;
    public Type TSCipherType { get; set; } = null!;
    public ConstructorBuilder TSCipherCtor { get; set; } = null!;
    public MethodBuilder TSCipherUpdateMethod { get; set; } = null!;
    public MethodBuilder TSCipherFinalMethod { get; set; } = null!;
    public MethodBuilder TSCipherSetAutoPaddingMethod { get; set; } = null!;
    public MethodBuilder TSCipherGetAuthTagMethod { get; set; } = null!;
    public MethodBuilder TSCipherSetAADMethod { get; set; } = null!;

    // $Decipher type - emitted for standalone crypto support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSDecipher
    public MethodBuilder CryptoCreateDecipheriv { get; set; } = null!;
    public Type TSDecipherType { get; set; } = null!;
    public ConstructorBuilder TSDecipherCtor { get; set; } = null!;
    public MethodBuilder TSDecipherUpdateMethod { get; set; } = null!;
    public MethodBuilder TSDecipherFinalMethod { get; set; } = null!;
    public MethodBuilder TSDecipherSetAutoPaddingMethod { get; set; } = null!;
    public MethodBuilder TSDecipherSetAuthTagMethod { get; set; } = null!;
    public MethodBuilder TSDecipherSetAADMethod { get; set; } = null!;

    // PBKDF2 and scrypt key derivation
    public MethodBuilder CryptoPbkdf2Sync { get; set; } = null!;
    public MethodBuilder CryptoScryptSync { get; set; } = null!;
    public MethodBuilder ScryptDeriveBytes { get; set; } = null!;

    // Timing-safe comparison
    public MethodBuilder CryptoTimingSafeEqual { get; set; } = null!;

    // $Sign type - emitted for standalone crypto signing support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSSign
    public MethodBuilder CryptoCreateSign { get; set; } = null!;
    public Type TSSignType { get; set; } = null!;
    public ConstructorBuilder TSSignCtor { get; set; } = null!;
    public MethodBuilder TSSignUpdateMethod { get; set; } = null!;
    public MethodBuilder TSSignSignMethod { get; set; } = null!;

    // $Verify type - emitted for standalone crypto verification support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSVerify
    public MethodBuilder CryptoCreateVerify { get; set; } = null!;
    public Type TSVerifyType { get; set; } = null!;
    public ConstructorBuilder TSVerifyCtor { get; set; } = null!;
    public MethodBuilder TSVerifyUpdateMethod { get; set; } = null!;
    public MethodBuilder TSVerifyVerifyMethod { get; set; } = null!;

    // AES-GCM helper methods (needed because AesGcm uses Span<T> parameters)
    public MethodBuilder AesGcmEncryptHelper { get; set; } = null!;
    public MethodBuilder AesGcmDecryptHelper { get; set; } = null!;

    // Crypto info methods (getHashes, getCiphers)
    public MethodBuilder CryptoGetHashes { get; set; } = null!;
    public MethodBuilder CryptoGetCiphers { get; set; } = null!;

    // Key pair generation
    public MethodBuilder CryptoGenerateKeyPairSync { get; set; } = null!;

    // DiffieHellman support
    public MethodBuilder CryptoCreateDiffieHellman { get; set; } = null!;
    public MethodBuilder CryptoGetDiffieHellman { get; set; } = null!;
    public Type TSDiffieHellmanType { get; set; } = null!;
    public ConstructorBuilder TSDiffieHellmanCtorPrimeLength { get; set; } = null!;
    public ConstructorBuilder TSDiffieHellmanCtorPrimeGenerator { get; set; } = null!;
    public ConstructorBuilder TSDiffieHellmanCtorGroup { get; set; } = null!;

    // ECDH support
    public MethodBuilder CryptoCreateECDH { get; set; } = null!;
    public Type TSECDHType { get; set; } = null!;
    public ConstructorBuilder TSECDHCtor { get; set; } = null!;

    // $Buffer type - emitted for standalone buffer support
    // NOTE: Must stay in sync with SharpTS.Runtime.Types.SharpTSBuffer
    public Type TSBufferType { get; set; } = null!;
    public ConstructorBuilder TSBufferCtor { get; set; } = null!;
    public ConstructorBuilder TSBufferCtorSize { get; set; } = null!;
    public MethodBuilder TSBufferLengthGetter { get; set; } = null!;
    public MethodBuilder TSBufferFromString { get; set; } = null!;
    public MethodBuilder TSBufferFromArray { get; set; } = null!;
    public MethodBuilder TSBufferAlloc { get; set; } = null!;
    public MethodBuilder TSBufferAllocUnsafe { get; set; } = null!;
    public MethodBuilder TSBufferConcat { get; set; } = null!;
    public MethodBuilder CalculateBuffersTotalLength { get; set; } = null!;
    public MethodBuilder TSBufferIsBuffer { get; set; } = null!;
    public MethodBuilder TSBufferToString { get; set; } = null!;
    public MethodBuilder TSBufferSlice { get; set; } = null!;
    public MethodBuilder TSBufferGetData { get; set; } = null!;
    public MethodBuilder TSBufferCopy { get; set; } = null!;
    public MethodBuilder TSBufferCompare { get; set; } = null!;
    public MethodBuilder TSBufferEquals { get; set; } = null!;
    public MethodBuilder TSBufferFill { get; set; } = null!;
    public MethodBuilder TSBufferWrite { get; set; } = null!;
    public MethodBuilder TSBufferReadUInt8 { get; set; } = null!;
    public MethodBuilder TSBufferWriteUInt8 { get; set; } = null!;
    public MethodBuilder TSBufferToJSON { get; set; } = null!;
    public MethodBuilder GetBufferMethod { get; set; } = null!;

    // Multi-byte read methods
    public MethodBuilder TSBufferReadInt8 { get; set; } = null!;
    public MethodBuilder TSBufferReadUInt16LE { get; set; } = null!;
    public MethodBuilder TSBufferReadUInt16BE { get; set; } = null!;
    public MethodBuilder TSBufferReadUInt32LE { get; set; } = null!;
    public MethodBuilder TSBufferReadUInt32BE { get; set; } = null!;
    public MethodBuilder TSBufferReadInt16LE { get; set; } = null!;
    public MethodBuilder TSBufferReadInt16BE { get; set; } = null!;
    public MethodBuilder TSBufferReadInt32LE { get; set; } = null!;
    public MethodBuilder TSBufferReadInt32BE { get; set; } = null!;
    public MethodBuilder TSBufferReadFloatLE { get; set; } = null!;
    public MethodBuilder TSBufferReadFloatBE { get; set; } = null!;
    public MethodBuilder TSBufferReadDoubleLE { get; set; } = null!;
    public MethodBuilder TSBufferReadDoubleBE { get; set; } = null!;
    public MethodBuilder TSBufferReadBigInt64LE { get; set; } = null!;
    public MethodBuilder TSBufferReadBigInt64BE { get; set; } = null!;
    public MethodBuilder TSBufferReadBigUInt64LE { get; set; } = null!;
    public MethodBuilder TSBufferReadBigUInt64BE { get; set; } = null!;

    // Multi-byte write methods
    public MethodBuilder TSBufferWriteInt8 { get; set; } = null!;
    public MethodBuilder TSBufferWriteUInt16LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteUInt16BE { get; set; } = null!;
    public MethodBuilder TSBufferWriteUInt32LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteUInt32BE { get; set; } = null!;
    public MethodBuilder TSBufferWriteInt16LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteInt16BE { get; set; } = null!;
    public MethodBuilder TSBufferWriteInt32LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteInt32BE { get; set; } = null!;
    public MethodBuilder TSBufferWriteFloatLE { get; set; } = null!;
    public MethodBuilder TSBufferWriteFloatBE { get; set; } = null!;
    public MethodBuilder TSBufferWriteDoubleLE { get; set; } = null!;
    public MethodBuilder TSBufferWriteDoubleBE { get; set; } = null!;
    public MethodBuilder TSBufferWriteBigInt64LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteBigInt64BE { get; set; } = null!;
    public MethodBuilder TSBufferWriteBigUInt64LE { get; set; } = null!;
    public MethodBuilder TSBufferWriteBigUInt64BE { get; set; } = null!;

    // Search methods
    public MethodBuilder TSBufferIndexOf { get; set; } = null!;
    public MethodBuilder TSBufferIncludes { get; set; } = null!;

    // Swap methods
    public MethodBuilder TSBufferSwap16 { get; set; } = null!;
    public MethodBuilder TSBufferSwap32 { get; set; } = null!;
    public MethodBuilder TSBufferSwap64 { get; set; } = null!;

    // Util module methods
    public MethodBuilder UtilFormat { get; set; } = null!;
    public MethodBuilder UtilInspect { get; set; } = null!;

    // Readline module methods
    public MethodBuilder ReadlineQuestionSync { get; set; } = null!;
    public MethodBuilder ReadlineCreateInterface { get; set; } = null!;

    // Child process module methods
    public MethodBuilder ChildProcessExecSync { get; set; } = null!;
    public MethodBuilder ChildProcessSpawnSync { get; set; } = null!;

    // Querystring module methods
    public MethodBuilder QuerystringParse { get; set; } = null!;
    public MethodBuilder QuerystringStringify { get; set; } = null!;

    // Zlib module methods
    public MethodBuilder ZlibGzipSync { get; set; } = null!;
    public MethodBuilder ZlibGunzipSync { get; set; } = null!;
    public MethodBuilder ZlibDeflateSync { get; set; } = null!;
    public MethodBuilder ZlibInflateSync { get; set; } = null!;
    public MethodBuilder ZlibDeflateRawSync { get; set; } = null!;
    public MethodBuilder ZlibInflateRawSync { get; set; } = null!;
    public MethodBuilder ZlibBrotliCompressSync { get; set; } = null!;
    public MethodBuilder ZlibBrotliDecompressSync { get; set; } = null!;
    public MethodBuilder ZlibZstdCompressSync { get; set; } = null!;
    public MethodBuilder ZlibZstdDecompressSync { get; set; } = null!;
    public MethodBuilder ZlibUnzipSync { get; set; } = null!;
    public MethodBuilder ZlibGetConstants { get; set; } = null!;

    // Assert module - emitted $AssertionError type for standalone assemblies
    // NOTE: Must stay in sync with AssertionError in AssertModuleInterpreter.cs
    public TypeBuilder TSAssertionErrorType { get; set; } = null!;
    public ConstructorBuilder TSAssertionErrorCtor { get; set; } = null!;
    public MethodBuilder TSAssertionErrorActualGetter { get; set; } = null!;
    public MethodBuilder TSAssertionErrorExpectedGetter { get; set; } = null!;
    public MethodBuilder TSAssertionErrorOperatorGetter { get; set; } = null!;

    // Assert module - helper methods
    public MethodBuilder AssertIsTruthy { get; set; } = null!;
    public MethodBuilder AssertStrictEquals { get; set; } = null!;
    public MethodBuilder AssertLooseEquals { get; set; } = null!;
    public MethodBuilder AssertDeepEquals { get; set; } = null!;

    // Assert module methods
    public MethodBuilder AssertOk { get; set; } = null!;
    public MethodBuilder AssertStrictEqual { get; set; } = null!;
    public MethodBuilder AssertNotStrictEqual { get; set; } = null!;
    public MethodBuilder AssertDeepStrictEqual { get; set; } = null!;
    public MethodBuilder AssertNotDeepStrictEqual { get; set; } = null!;
    public MethodBuilder AssertThrows { get; set; } = null!;
    public MethodBuilder AssertDoesNotThrow { get; set; } = null!;
    public MethodBuilder AssertFail { get; set; } = null!;
    public MethodBuilder AssertEqual { get; set; } = null!;
    public MethodBuilder AssertNotEqual { get; set; } = null!;

    // URL module methods
    public MethodBuilder UrlCreateUrlObject { get; set; } = null!;
    public MethodBuilder UrlParse { get; set; } = null!;
    public MethodBuilder UrlFormat { get; set; } = null!;
    public MethodBuilder UrlResolve { get; set; } = null!;

    // Built-in module methods (module name -> method name -> MethodBuilder)
    // Used for creating TSFunction wrappers when importing named exports
    private readonly Dictionary<string, Dictionary<string, MethodBuilder>> _builtInModuleMethods = new();

    /// <summary>
    /// Registers a built-in module method.
    /// </summary>
    public void RegisterBuiltInModuleMethod(string moduleName, string methodName, MethodBuilder method)
    {
        if (!_builtInModuleMethods.TryGetValue(moduleName, out var methods))
        {
            methods = new Dictionary<string, MethodBuilder>();
            _builtInModuleMethods[moduleName] = methods;
        }
        methods[methodName] = method;
    }

    /// <summary>
    /// Gets a built-in module method for creating a TSFunction wrapper.
    /// </summary>
    public MethodBuilder? GetBuiltInModuleMethod(string moduleName, string methodName)
    {
        if (_builtInModuleMethods.TryGetValue(moduleName, out var methods) &&
            methods.TryGetValue(methodName, out var method))
        {
            return method;
        }
        return null;
    }
}
