using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace SharpTS.Sdk.Tasks;

/// <summary>
/// Emits direct constructor calls for GUI control providers. This deliberately avoids assembly
/// scanning and reflection so provider closure remains visible to trimming and Native AOT.
/// </summary>
public sealed class WriteGuiControlProviderRegistrationTask : Task
{
    /// <summary>
    /// Path where the generated registration code will be written.
    /// </summary>
    [Required]
    public string OutputPath { get; set; } = string.Empty;

    /// <summary>
    /// Array of control provider types to register.
    /// </summary>
    public ITaskItem[] ProviderTypes { get; set; } = [];

    /// <summary>
    /// Executes the task to generate control provider registration code.
    /// </summary>
    /// <returns>True if successful; otherwise, false.</returns>
    public override bool Execute()
    {
        try
        {
            string[] types = ProviderTypes
                .Select(item => item.ItemSpec.Trim())
                .Where(value => value.Length != 0)
                .ToArray();
            string? duplicate = types.GroupBy(value => value, StringComparer.Ordinal)
                .FirstOrDefault(group => group.Count() > 1)?.Key;
            if (duplicate is not null)
                throw new InvalidOperationException($"Duplicate SharpTS GUI control provider type '{duplicate}'.");
            foreach (string type in types)
                if (!IsQualifiedTypeName(type))
                    throw new InvalidOperationException(
                        $"SharpTS GUI control provider type '{type}' must be a non-generic qualified C# type name.");

            var source = new StringBuilder()
                .AppendLine("// <auto-generated />")
                .AppendLine("#nullable enable")
                .AppendLine("namespace SharpTS.Gui.Generated;")
                .AppendLine()
                .AppendLine("internal static class ControlProviderRegistration")
                .AppendLine("{")
                .AppendLine("    internal static global::System.IDisposable Register() =>")
                .AppendLine("        global::SharpTS.Gui.DesktopBridge.RegisterControlProviders(");
            for (int index = 0; index < types.Length; index++)
            {
                string comma = index == types.Length - 1 ? string.Empty : ",";
                source.Append("            new ").Append(types[index]).Append("()").Append(comma).AppendLine();
            }
            source.AppendLine("        );").AppendLine("}");

            string output = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(output)!);
            string contents = source.ToString();
            if (!File.Exists(output) || !string.Equals(File.ReadAllText(output), contents, StringComparison.Ordinal))
                File.WriteAllText(output, contents, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(exception, showStackTrace: false);
            return false;
        }
    }

    private static bool IsQualifiedTypeName(string value)
    {
        string candidate = value.StartsWith("global::", StringComparison.Ordinal) ? value[8..] : value;
        if (candidate.Length == 0 || candidate[0] == '.' || candidate[^1] == '.')
            return false;
        foreach (string segment in candidate.Split('.'))
        {
            if (segment.Length == 0 || !(char.IsLetter(segment[0]) || segment[0] == '_'))
                return false;
            if (segment.Any(character => !(char.IsLetterOrDigit(character) || character == '_')))
                return false;
        }
        return true;
    }
}
