import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { readTrace } from "./trace.mjs";

const workspace = path.resolve(process.argv[2]);
const { config, messages, histories, requests } = await readTrace(workspace);
const initialize = messages.find((item) => item.direction === "->" && item.message.method === "initialize");
assert.ok(initialize, "native initialize missing");
assert.equal(initialize.message.params.capabilities.workspace.workspaceEdit.documentChanges, true);
const initialized = messages.find((item) => item.direction === "<-" && item.message.id === initialize.message.id);
const caps = initialized.message.result.capabilities;
for (const name of ["hoverProvider", "completionProvider", "signatureHelpProvider", "definitionProvider", "referencesProvider", "renameProvider"]) assert.ok(caps[name], `${name} missing`);
for (const name of ["inlayHintProvider", "semanticTokensProvider", "foldingRangeProvider", "documentFormattingProvider", "documentRangeFormattingProvider", "documentOnTypeFormattingProvider"]) assert.ok(!caps[name], `${name} advertised`);
assert.ok(!messages.some((item) => /^textDocument\/(?:formatting|rangeFormatting|onTypeFormatting)$/.test(item.message.method)), "LSP formatting request");
assert.ok(!messages.some((item) => item.message.method === "client/registerCapability" && item.message.params.registrations.some((registration) => /formatting|inlayHint|semanticTokens|foldingRange/i.test(registration.method))));
const successes = (method) => requests(method).filter((item) => item.response && !item.response.message.error && item.response.message.result);
const hoverText = (item) => JSON.stringify(item.response.message.result.contents);
const hovers = successes("textDocument/hover");
assert.ok(hovers.some((item) => hoverText(item).includes("result: number")), "ordinary semantic hover missing");
const definition = successes("textDocument/definition").find((item) => {
  const result = item.response.message.result;
  return (Array.isArray(result) ? result : [result]).some((location) => (location.uri ?? location.targetUri).toLowerCase().endsWith("/dependency.ts"));
});
assert.ok(definition, "native cross-file definition missing");
const references = successes("textDocument/references").find((item) => ["/main.ts", "/dependency.ts"].every((suffix) => item.response.message.result.some((location) => location.uri.toLowerCase().endsWith(suffix))));
assert.ok(references, "member references missing");
const completion = successes("textDocument/completion").find((item) => {
  const items = item.response.message.result.items ?? item.response.message.result;
  return ["add", "extra", "value"].every((name) => items.some((candidate) => candidate.label === name));
});
assert.ok(completion, "receiver completion from dirty dependency missing");
const dirtyDependency = histories.findLast((item) => item.index < completion.request.index && item.uri.toLowerCase().endsWith("/dependency.ts"));
assert.ok(dirtyDependency.text.includes("extra: number = 4") && dirtyDependency.method === "textDocument/didChange", "dependency was not dirty");
assert.ok(!histories.some((item) => item.index < completion.request.index && item.uri.toLowerCase().endsWith("/dependency.ts") && item.method === "textDocument/didSave"));
const signature = successes("textDocument/signatureHelp").find((item) => item.document?.text.includes("counter.add(\n") && item.response.message.result.signatures.some((candidate) => candidate.label.includes("left: number") && candidate.label.includes("right: number")));
assert.ok(signature, "accepted native completion / unfinished-call signature missing");
assert.equal(signature.response.message.result.activeParameter, 0);
assert.equal(signature.response.message.result.activeSignature, undefined, "recovered hole selected an overload");
const privateRename = successes("textDocument/rename").find((item) => item.request.message.params.newName === "#renamedSecret");
assert.ok(privateRename, "private rename missing");
const privateChanges = privateRename.response.message.result.documentChanges;
assert.equal(privateChanges.length, 1);
assert.equal(privateChanges[0].textDocument.version, privateRename.document.version);
assert.equal(privateChanges[0].edits.length, 2);
assert.ok(privateChanges[0].edits.every((edit) => edit.newText === "#renamedSecret" && edit.range.end.character - edit.range.start.character === "#secret".length));
assert.ok(histories.some((item) => item.index > privateRename.response.index && item.uri.toLowerCase().endsWith("/dependency.ts") && item.text.includes("this.#renamedSecret") && !item.text.includes("#secret")), "native private edit not applied");
assert.ok(hovers.some((item) => hoverText(item).includes("#renamedSecret: number")), "fresh private binding unavailable");
const lexicalRename = successes("textDocument/rename").find((item) => item.request.message.params.newName === "renamedLocal");
assert.ok(lexicalRename, "lexical rename missing");
const diagnostics = messages.filter((item) => item.direction === "<-" && item.message.method === "textDocument/publishDiagnostics");
assert.ok(diagnostics.some((item) => item.message.params.diagnostics.some((diagnostic) => /wrong|string/.test(diagnostic.message))), "ordinary type diagnostics missing");
const formatted = [];
for (const [file, stage, needle] of [["main.ts", "main-valid", "result: number"], ["view.tsx", "view-dirty", "title:"] , ["dependency.ts", "dependency-dirty", "#renamedSecret: number"]]) {
  const actual = await fs.readFile(path.join(workspace, file), "utf8");
  let source = await fs.readFile(path.join(workspace, `${stage}.txt`), "utf8");
  if (file === "main.ts") source = source.replaceAll("lexical", "renamedLocal");
  const format = spawnSync(config.formatter.executable, [config.formatter.module, "--stdin-filepath", path.join(workspace, file)], { cwd: workspace, input: source, encoding: "utf8", windowsHide: true, timeout: 10000 });
  assert.equal(format.status, 0, format.stderr);
  assert.equal(actual, format.stdout, `${file}: pinned formatter bytes differ`);
  const saves = histories.filter((item) => item.uri.toLowerCase().endsWith(`/${file}`) && item.method === "textDocument/didSave");
  const save = saves.findLast((item) => item.text === actual);
  assert.ok(save, `${file}: didSave missing`);
  assert.ok(hovers.some((item) => item.request.index < save.index && item.document.uri.toLowerCase().endsWith(`/${file}`) && hoverText(item).includes(needle)), `${file}: pre-save hover missing`);
  const after = hovers.find((item) => item.request.index > save.index && item.document.uri.toLowerCase().endsWith(`/${file}`) && hoverText(item).includes(needle));
  assert.ok(after, `${file}: fresh post-save hover missing`);
  const finalDiagnostics = diagnostics.findLast((item) => item.message.params.uri.toLowerCase().endsWith(`/${file}`));
  assert.equal(finalDiagnostics?.message.params.version, save.version, `${file}: diagnostic version differs`);
  assert.equal(finalDiagnostics.message.params.diagnostics.length, 0, `${file}: final source did not check cleanly`);
  formatted.push({ file, version: save.version, sha256: createHash("sha256").update(actual).digest("hex"), saveIndex: save.index, afterHoverId: after.request.message.id });
}
assert.ok(messages.some((item) => item.direction === "->" && item.message.method === "shutdown"), "native shutdown missing");
const result = { completed: true, timestamp: new Date().toISOString(), editor: config.editor, mode: "full", diagnostics: "all", commit: config.commit, serverSha256: config.serverSha256, node: config.nodeVersion, prettier: config.formatter.version, platform: config.platform, architecture: config.architecture, versionedPrivateEdits: true, ordinaryHover: true, dirtyDependencyCompletion: true, nativeCompletionApplied: true, unfinishedSignature: true, definition: true, memberReferences: true, lexicalRenameApplied: true, privateRenameApplied: true, ordinaryDiagnosticsCleared: true, lspFormattingRequests: 0, formatted, workspace, log: config.log };
await fs.writeFile(path.join(workspace, "result.json"), JSON.stringify(result, null, 2) + "\n");
console.log(JSON.stringify(result, null, 2));
