[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'NuGetRelease.psm1') -Force
$script:passed = 0; $script:failed = 0; $releaseVersion = '2.0.0'
$packageIds = @('SharpTS.LanguageServer', 'SharpTS.Hosting', 'SharpTS.Sdk', 'SharpTS', 'SharpTS.Gui.Sdk')
function Assert-True([bool]$Condition, [string]$Message) { if (-not $Condition) { throw $Message } }
function Assert-ThrowsContaining([scriptblock]$Action, [string]$ExpectedText) { try { & $Action } catch { if ($_.Exception.Message -notlike "*$ExpectedText*") { throw "Expected '$ExpectedText', got: $($_.Exception.Message)" }; return }; throw "Expected '$ExpectedText'." }
function Invoke-Test([string]$Name, [scriptblock]$Test) { try { & $Test; $script:passed++; Write-Host "PASS: $Name" } catch { $script:failed++; Write-Error "FAIL: $Name`n$($_.Exception.Message)" -ErrorAction Continue } }
function New-TestFixture {
    $root = Join-Path ([IO.Path]::GetTempPath()) "sharpts-nuget-release-$([guid]::NewGuid().ToString('N'))"; $dir = Join-Path $root 'nupkg'; New-Item -ItemType Directory $dir | Out-Null
    $manifestPath = Join-Path $root 'nuget-packages.json'; [ordered]@{ schemaVersion = 2; packages = @($packageIds | ForEach-Object { [ordered]@{ id = $_ } }) } | ConvertTo-Json -Depth 5 | Set-Content $manifestPath
    foreach ($id in $packageIds) { 'test' | Set-Content (Join-Path $dir "$id.$releaseVersion.nupkg") }
    [pscustomobject]@{ Root=$root; PackageDirectory=$dir; ManifestPath=$manifestPath; Manifest=Get-NuGetReleaseManifest $manifestPath }
}
function New-VersionMap { $map=@{}; foreach ($id in $packageIds) { $map[$id]=[Collections.ArrayList]@('1.0.7') }; $map }

Invoke-Test 'schema v2 rejects per-package release overrides' { $f=New-TestFixture; try { foreach ($field in @('version','publish','sha256')) { $d=[ordered]@{schemaVersion=2;packages=@($packageIds|%{[ordered]@{id=$_}})}; $d.packages[0][$field]=if($field -eq 'publish'){$false}else{'override'}; $d|ConvertTo-Json -Depth 5|Set-Content $f.ManifestPath; Assert-ThrowsContaining { Get-NuGetReleaseManifest $f.ManifestPath } "unsupported field(s): $field" } } finally { Remove-Item $f.Root -Recurse -Force } }
Invoke-Test 'preflight requires all five tag-versioned files' { $f=New-TestFixture; try { $v=New-VersionMap; $fetch={param($Id,$Uri)@($v[$Id])}.GetNewClosure(); Assert-NuGetReleasePreflight $f.Manifest $f.PackageDirectory $releaseVersion $f.Root -FetchPackageVersions $fetch; Remove-Item (Join-Path $f.PackageDirectory "SharpTS.Gui.Sdk.$releaseVersion.nupkg"); Assert-ThrowsContaining { Assert-NuGetReleasePreflight $f.Manifest $f.PackageDirectory $releaseVersion $f.Root -FetchPackageVersions $fetch } "SharpTS.Gui.Sdk.$releaseVersion.nupkg" } finally { Remove-Item $f.Root -Recurse -Force } }
Invoke-Test 'publication uses one version and all five filenames' { $f=New-TestFixture; try { $v=New-VersionMap; $files=[Collections.Generic.List[string]]::new(); $push={param($Path,$Id,$Version,$Key,$Source)$files.Add([IO.Path]::GetFileName($Path));[void]$v[$Id].Add($Version)}.GetNewClosure(); $fetch={param($Id,$Uri)@($v[$Id])}.GetNewClosure(); Publish-NuGetPackages $f.Manifest $f.PackageDirectory $releaseVersion key -VerificationAttempts 1 -VerificationDelaySeconds 0 -PushPackage $push -FetchPackageVersions $fetch; $expected=@($packageIds|%{"$($_).$releaseVersion.nupkg"}|Sort-Object); Assert-True (-not(Compare-Object $expected @($files|Sort-Object) -SyncWindow 0)) 'Expected filenames differ.' } finally { Remove-Item $f.Root -Recurse -Force } }
Invoke-Test 'publication waits for delayed NuGet indexing' { $f=New-TestFixture; try { $v=New-VersionMap;$counts=@{};$sleeps=[pscustomobject]@{Value=0};$expected=$releaseVersion;$push={param($Path,$Id,$Version,$Key,$Source)};$fetch={param($Id,$Uri)$counts[$Id]=1+($counts[$Id] ?? 0);if($counts[$Id] -ge 3 -and $v[$Id] -notcontains $expected){[void]$v[$Id].Add($expected)};@($v[$Id])}.GetNewClosure();$sleep={param($Seconds)$sleeps.Value++}.GetNewClosure();Publish-NuGetPackages $f.Manifest $f.PackageDirectory $releaseVersion key -VerificationAttempts 2 -VerificationDelaySeconds 0 -PushPackage $push -FetchPackageVersions $fetch -Sleep $sleep;Assert-True ($sleeps.Value -eq 1) 'Expected one indexing wait.' } finally { Remove-Item $f.Root -Recurse -Force } }
Invoke-Test 'push error is nonfatal after final inventory visibility' { $f=New-TestFixture; try { $v=New-VersionMap;$push={param($Path,$Id,$Version,$Key,$Source)[void]$v[$Id].Add($Version);if($Id -eq 'SharpTS.Gui.Sdk'){throw 'response lost'}}.GetNewClosure();$fetch={param($Id,$Uri)@($v[$Id])}.GetNewClosure();Publish-NuGetPackages $f.Manifest $f.PackageDirectory $releaseVersion key -VerificationAttempts 1 -VerificationDelaySeconds 0 -PushPackage $push -FetchPackageVersions $fetch } finally { Remove-Item $f.Root -Recurse -Force } }
Invoke-Test 'partial publish rerun pushes only the missing version' { $f=New-TestFixture; try { $v=New-VersionMap;$attempts=[Collections.Generic.List[string]]::new();$first=[pscustomobject]@{Value=$true};$push={param($Path,$Id,$Version,$Key,$Source)$attempts.Add($Id);if($first.Value -and $Id -eq 'SharpTS.Hosting'){throw 'permission failure'};if($v[$Id] -notcontains $Version){[void]$v[$Id].Add($Version)}}.GetNewClosure();$fetch={param($Id,$Uri)@($v[$Id])}.GetNewClosure();Assert-ThrowsContaining { Publish-NuGetPackages $f.Manifest $f.PackageDirectory $releaseVersion key -VerificationAttempts 1 -VerificationDelaySeconds 0 -PushPackage $push -FetchPackageVersions $fetch } 'permission failure';$first.Value=$false;$before=$attempts.Count;Publish-NuGetPackages $f.Manifest $f.PackageDirectory $releaseVersion key -VerificationAttempts 1 -VerificationDelaySeconds 0 -PushPackage $push -FetchPackageVersions $fetch;$rerun=@($attempts|Select-Object -Skip $before);Assert-True ($rerun.Count -eq 1 -and $rerun[0] -eq 'SharpTS.Hosting') 'Rerun did not skip visible versions.' } finally { Remove-Item $f.Root -Recurse -Force } }
Write-Host "NuGet release helper tests: $script:passed passed, $script:failed failed."; if($script:failed){exit 1}
