[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$fixture = Join-Path $root ('artifacts/code-quality-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $fixture -Force | Out-Null

function Assert-Build([string]$Name, [string]$Source, [string[]]$Expected = @()) {
    Set-Content -LiteralPath (Join-Path $fixture 'Probe.cs') -Value $Source
    $output = & dotnet build (Join-Path $fixture 'Probe.csproj') -c Release --no-incremental `
        -m:1 -nr:false -p:UseSharedCompilation=false 2>&1 | Out-String
    $exitCode = $LASTEXITCODE
    Set-Content -LiteralPath (Join-Path $fixture "$Name.log") -Value $output
    if ($Expected.Count -eq 0) {
        if ($exitCode -ne 0) { throw "$Name should pass:`n$output" }
    }
    else {
        if ($exitCode -eq 0) { throw "$Name should fail with $Expected, but built successfully.`n$output" }
        foreach ($diagnostic in $Expected) {
            if ($output -notmatch "error $diagnostic\b") { throw "$Name did not report error ${diagnostic}:`n$output" }
        }
        if ($output -match 'error (?!IDE0051\b|IDE0052\b)[A-Z]+\d+') {
            throw "$Name failed for an unrelated reason:`n$output"
        }
    }
    Write-Host "PASS: $Name"
}

Push-Location $root
try {
    # Inherit the real repository props/editorconfig; do not restate severities.
    Set-Content -LiteralPath (Join-Path $fixture 'Probe.csproj') -Value @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
</Project>
'@
    Set-Content -LiteralPath (Join-Path $fixture 'Probe.Partial.cs') -Value @'
public partial class Probe
{
    public int Run() => UsedAcrossPartial();
    private int UsedAcrossPartial() => 42;
}
'@
    Assert-Build 'unused-method' 'public partial class Probe { private void Dead() {} }' @('IDE0051')
    Assert-Build 'unread-field' 'public partial class Probe { private int unread; public void Write() { unread = 1; } }' @('IDE0052')
    Assert-Build 'partial-reference' 'public partial class Probe { public int OtherPart() => UsedAcrossPartial(); }'
    Assert-Build 'registered-and-reflected' @'
using System;
using System.Reflection;
public partial class Probe
{
    private static void Callback() {}
    private void Reflected() {}
    public Action Register() => Callback;
    public MethodInfo? Lookup() => typeof(Probe).GetMethod(nameof(Reflected), BindingFlags.NonPublic | BindingFlags.Instance);
}
'@
    Assert-Build 'justified-suppression' @'
using System.Diagnostics.CodeAnalysis;
public partial class Probe
{
    [SuppressMessage("Style", "IDE0051", Justification = "Fixture: invoked by an external string-based registry.")]
    private void ExternalCallback() {}
}
'@
    Set-Content -LiteralPath (Join-Path $fixture 'Generated.g.cs') -Value @'
// <auto-generated/>
class Generated { private void GeneratedUnused() {} }
'@
    Assert-Build 'generated-exclusion' 'public partial class Probe {}'
    # Characterize the analyzer boundary: this is reference counting, not reachability.
    Assert-Build 'unreachable-cycle-limitation' 'public partial class Probe { private void A() => B(); private void B() => A(); }'
    # Pinned SDK limitation: a qualified nameof suppresses unused-member reports
    # for the containing type. QLT001 covers the audited emitters independently.
    Assert-Build 'qualified-nameof-limitation' 'public partial class Probe { private void Dead() {} public string Name() => nameof(System.Console.WriteLine); }'

    & dotnet run --project eng/CodeQuality -c Release -- --self-test
    if ($LASTEXITCODE -ne 0) { throw 'Duplicate checker self-tests failed.' }

    # Exercise the real executable's exit status and diagnostics on mutations.
    $mutationRoot = Join-Path $fixture 'mutation-repo'
    $mutationSource = Join-Path $mutationRoot 'src/SharpTS/Compilation'
    New-Item -ItemType Directory -Force -Path $mutationSource, (Join-Path $mutationRoot 'eng/CodeQuality') | Out-Null
    Set-Content -LiteralPath (Join-Path $mutationRoot 'eng/CodeQuality/duplicates.json') -Value '[]'
    $body = '{ int sum = 0; ' + ((0..14 | ForEach-Object { "sum += $_; " }) -join '') + 'return sum; }'
    Set-Content -LiteralPath (Join-Path $mutationSource 'Mutation.cs') -Value @"
class Copies { public int One() $body public int Two() $body }
partial class RuntimeEmitter { private void Dead() {} public string Name() => nameof(System.Console.WriteLine); }
"@
    $mutationOutput = & dotnet run --project eng/CodeQuality -c Release --no-build -- $mutationRoot 2>&1 | Out-String
    if ($LASTEXITCODE -ne 1 -or $mutationOutput -notmatch 'QLT001' -or $mutationOutput -notmatch 'DUP001') {
        throw "Mutations did not fail with both actionable diagnostics:`n$mutationOutput"
    }
    Write-Host 'PASS: CLI unused-emitter and duplicate mutations fail with QLT001 and DUP001'
    New-Item -ItemType Directory -Force -Path (Join-Path $mutationRoot 'tests/fixtures') | Out-Null
    Set-Content -LiteralPath (Join-Path $mutationRoot 'tests/fixtures/Intentional.cs') -Value "class Fixture { public int One() $body public int Two() $body }"
    Set-Content -LiteralPath (Join-Path $mutationSource 'Generated.g.cs') -Value "// <auto-generated/>`nclass Generated { public int One() $body public int Two() $body }"
    Set-Content -LiteralPath (Join-Path $mutationSource 'Mutation.cs') -Value 'partial class RuntimeEmitter { private void Callback() {} public string Register() => nameof(Callback); }'
    $cleanOutput = & dotnet run --project eng/CodeQuality -c Release --no-build -- $mutationRoot 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) { throw "Registered entry point and intentional exclusions should pass:`n$cleanOutput" }
    Write-Host 'PASS: CLI reflection registration and generated/test fixture exclusions'
    & dotnet run --project eng/CodeQuality -c Release --no-build -- $root
    if ($LASTEXITCODE -ne 0) { throw 'Duplicate regression check failed.' }
    Write-Host "Code quality gates passed. Fixture logs: $fixture"
}
finally { Pop-Location }
